project_id = "zwebwrbbrcmajkuptpwq"

[functions.generate-laudo]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = false

[functions.export-pdf]
verify_jwt = true

[functions.import-pdf]
verify_jwt = true

[functions.verify-pdf]
verify_jwt = false

[functions.cakto-webhook]
verify_jwt = false

[functions.generate-prescription-pdf]
verify_jwt = true