// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-pacientes.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pacientes_default = defineTool({
  name: "list_pacientes",
  title: "Listar pacientes",
  description: "Lista os pacientes do m\xE9dico autenticado (mais recentes primeiro).",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("M\xE1ximo de resultados (padr\xE3o 20)."),
    search: z.string().optional().describe("Filtro por nome do paciente (opcional).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = client(ctx).from("patients").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) q = q.ilike("full_name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { patients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-laudos.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_laudos_default = defineTool2({
  name: "list_laudos",
  title: "Listar laudos",
  description: "Lista os laudos m\xE9dicos do usu\xE1rio autenticado.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("M\xE1ximo de resultados (padr\xE3o 20)."),
    status: z2.string().optional().describe("Filtrar por status (ex: 'completed', 'processing').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    let q = client2(ctx).from("laudos").select("id, title, status, specialty, created_at, pdf_url").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { laudos: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-laudo.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_laudo_default = defineTool3({
  name: "get_laudo",
  title: "Obter laudo",
  description: "Retorna um laudo completo pelo ID (respeita RLS do usu\xE1rio).",
  inputSchema: {
    id: z3.string().uuid().describe("ID do laudo (UUID).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await client3(ctx).from("laudos").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Laudo n\xE3o encontrado" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { laudo: data }
    };
  }
});

// src/lib/mcp/tools/search-medications.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_medications_default = defineTool4({
  name: "search_medications",
  title: "Buscar medicamentos",
  description: "Busca medicamentos no cat\xE1logo (opcionalmente priorizando por CID-10).",
  inputSchema: {
    query: z4.string().min(1).describe("Termo de busca: nome comercial, princ\xEDpio ativo ou classe."),
    cid: z4.string().optional().describe("C\xF3digo CID-10 do paciente para priorizar recomenda\xE7\xF5es.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, cid }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "N\xE3o autenticado" }], isError: true };
    }
    const { data, error } = await client4(ctx).rpc("search_medications", { q: query, cid: cid ?? null });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { medications: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zwebwrbbrcmajkuptpwq";
var mcp_default = defineMcp({
  name: "mindmed-mcp",
  title: "MindMed",
  version: "0.1.0",
  instructions: "Ferramentas do MindMed para assistentes de IA. Permite consultar pacientes, laudos e o cat\xE1logo de medicamentos do m\xE9dico autenticado. Todas as opera\xE7\xF5es s\xE3o somente-leitura e respeitam a autoriza\xE7\xE3o (RLS) do usu\xE1rio.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_pacientes_default, list_laudos_default, get_laudo_default, search_medications_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
