WITH new_meds(nome_comercial, principio_ativo, laboratorio, apresentacao, posologia_referencia, classe_terapeutica, is_parceiro, parceiro_nome, ativo, tarja, tipo_receita) AS (
VALUES
('Losartana Potássica EMS','Losartana potássica','EMS','Comp. rev. 25 / 50 / 100 mg; combos c/ HCTZ e c/ anlodipino','50-100 mg 1x/dia','Cardiologia',true,'EMS',true,'livre','branca_comum'),
('Zart','Losartana potássica','Eurofarma','50 mg cx 30; Zart H c/ HCTZ','50-100 mg 1x/dia','Cardiologia',true,'Eurofarma',true,'livre','branca_comum'),
('Besilato de Anlodipino EMS','Anlodipino','EMS','Comp. 5 / 10 mg','5-10 mg 1x/dia','Cardiologia',true,'EMS',true,'livre','branca_comum'),
('Besilato de anlodipino Eurofarma','Anlodipino','Eurofarma','5 mg cx 30; Anaten (c/ atenolol)','5-10 mg 1x/dia','Cardiologia',true,'Eurofarma',true,'livre','branca_comum'),
('Atenolol EMS','Atenolol','EMS','Comp. 25 / 50 / 100 mg','25-100 mg 1x/dia','Cardiologia',true,'EMS',true,'livre','branca_comum'),
('Carvedilol EMS','Carvedilol','EMS','Comp. 3,125 / 6,25 / 12,5 / 25 mg','3,125 mg 2x/dia até 25 mg 2x/dia','Cardiologia',true,'EMS',true,'livre','branca_comum'),
('Maleato de Enalapril EMS','Enalapril','EMS','Comp. 5 / 10 / 20 mg','10-40 mg/dia','Cardiologia',true,'EMS',true,'livre','branca_comum'),
('Hidroclorotiazida EMS','Hidroclorotiazida','EMS','Comp. 25 / 50 mg','12,5-25 mg 1x/dia','Cardiologia',true,'EMS',true,'livre','branca_comum'),
('Sinvastatina EMS','Sinvastatina','EMS','Comp. 10 / 20 / 40 mg','20-40 mg 1x/dia, à noite','Cardiologia',true,'EMS',true,'livre','branca_comum'),
('Atorvastatina Cálcica EMS','Atorvastatina cálcica','EMS','Comp. rev. 10 / 20 / 40 / 80 mg','10-80 mg 1x/dia','Cardiologia',true,'EMS',true,'livre','branca_comum'),
('Vast','Atorvastatina cálcica','Eurofarma','10 / 20 / 40 mg','10-80 mg 1x/dia','Cardiologia',true,'Eurofarma',true,'livre','branca_comum'),
('Rosuvastatina Cálcica EMS','Rosuvastatina cálcica','EMS','Comp. rev. 5 / 10 / 20 / 40 mg','10 mg 1x/dia','Cardiologia',true,'EMS',true,'livre','branca_comum'),
('RUVA','Rosuvastatina cálcica','Eurofarma','5 / 10 / 20 mg cx 30','10 mg 1x/dia','Cardiologia',true,'Eurofarma',true,'livre','branca_comum'),
('Bissulfato de Clopidogrel EMS','Clopidogrel','EMS','Comp. rev. 75 mg','75 mg 1x/dia','Cardiologia',true,'EMS',true,'livre','branca_comum'),
('Plaq','Clopidogrel','Eurofarma','75 mg cx 10 / 30','75 mg 1x/dia','Cardiologia',true,'Eurofarma',true,'livre','branca_comum'),
('Espironolactona EMS','Espironolactona','EMS','Comp. 25 / 50 / 100 mg','25-100 mg/dia','Cardiologia',true,'EMS',true,'livre','branca_comum'),
('Espironolactona Eurofarma','Espironolactona','Eurofarma','25 / 50 mg cx 30','25-100 mg/dia','Cardiologia',true,'Eurofarma',true,'livre','branca_comum'),
('Cloridrato de Metformina EMS','Metformina','EMS','Comp. 500 / 850 / 1000 mg (incl. XR)','500-2550 mg/dia','Endocrinologia',true,'EMS',true,'livre','branca_comum'),
('Glibenclamida EMS','Glibenclamida','EMS','Comp. 5 mg','2,5-5 mg 1x/dia','Endocrinologia',true,'EMS',true,'livre','branca_comum'),
('Gliclazida EMS','Gliclazida','EMS','Comp. LP 30 / 60 mg','30-120 mg 1x/dia','Endocrinologia',true,'EMS',true,'livre','branca_comum'),
('Glimepirida EMS','Glimepirida','EMS','Comp. 1 / 2 / 4 mg','1-4 mg 1x/dia','Endocrinologia',true,'EMS',true,'livre','branca_comum'),
('Betes','Glimepirida','Eurofarma','Comp. 1 / 2 / 4 mg','1-4 mg 1x/dia','Endocrinologia',true,'Eurofarma',true,'livre','branca_comum'),
('Dapagliflozina EMS','Dapagliflozina','EMS','Comp. rev. 10 mg','10 mg 1x/dia','Endocrinologia',true,'EMS',true,'livre','branca_comum'),
('Glif','Dapagliflozina','Eurofarma','10 mg cx 30','10 mg 1x/dia','Endocrinologia',true,'Eurofarma',true,'livre','branca_comum'),
('Empagliflozina EMS','Empagliflozina','EMS','Comp. rev. 10 / 25 mg','10-25 mg 1x/dia','Endocrinologia',true,'EMS',true,'livre','branca_comum'),
('Poviztra','Semaglutida','Eurofarma','Caneta SC semanal 0,25-2,4 mg (obesidade)','Titular semanalmente','Endocrinologia',true,'Eurofarma',true,'livre','branca_comum'),
('Extensior','Semaglutida','Eurofarma','Caneta SC semanal (DM2)','Até 1 mg/sem','Endocrinologia',true,'Eurofarma',true,'livre','branca_comum'),
('Olire','Liraglutida','EMS','Caneta 6 mg/mL SC diária (obesidade)','Até 3 mg/dia','Endocrinologia',true,'EMS',true,'livre','branca_comum'),
('Lirux','Liraglutida','EMS','Caneta 6 mg/mL SC diária (DM2)','1,2-1,8 mg/dia','Endocrinologia',true,'EMS',true,'livre','branca_comum'),
('Fosfato de Sitagliptina EMS','Sitagliptina','EMS','Comp. rev. 25 / 50 / 100 mg','100 mg 1x/dia','Endocrinologia',true,'EMS',true,'livre','branca_comum'),
('Cloridrato de Sertralina EMS','Sertralina','EMS','Comp. rev. 50 / 100 mg','50 mg 1x/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Assert','Sertralina','Eurofarma','50 / 100 mg','50 mg 1x/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Afetus','Sertralina','Eurofarma','25 / 50 / 100 mg','50 mg 1x/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Oxalato de Escitalopram EMS','Escitalopram','EMS','Comp. rev. 10 / 15 / 20 mg','10 mg 1x/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Esc','Escitalopram','Eurofarma','10 / 20 mg; sol. oral','10 mg 1x/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Esc ODT','Escitalopram','Eurofarma','ODT 5-20 mg','10 mg 1x/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Cloridrato de Fluoxetina EMS','Fluoxetina','EMS','Cáps./comp. 20 mg','20 mg 1x/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Fluoxetina Eurofarma','Fluoxetina','Eurofarma','Cáps. 20 mg','20 mg 1x/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Cloridrato de Paroxetina EMS','Paroxetina','EMS','Comp. rev. 20 mg','20 mg 1x/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Pondera','Paroxetina','Eurofarma','20 / 40 mg','20 mg 1x/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Pondera XR','Paroxetina','Eurofarma','Liberação prolongada','20 mg 1x/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Cloridrato de Venlafaxina EMS','Venlafaxina','EMS','Cáps. LP 37,5 / 75 / 150 mg','75 mg 1x/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Venlaxin XR','Venlafaxina','Eurofarma','Cáps. LP 37,5 / 75 / 150 mg','75 mg 1x/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Succinato de Desvenlafaxina EMS','Desvenlafaxina','EMS','Comp. LP 50 / 100 mg','50 mg 1x/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Desve','Desvenlafaxina','Eurofarma','Comp. LP 50 / 100 mg','50 mg 1x/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Cloridrato de Bupropiona EMS','Bupropiona','EMS','Comp. LP 150 / 300 mg','150-300 mg/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Bup','Bupropiona','Eurofarma','150 mg','150-300 mg/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Bup XL','Bupropiona','Eurofarma','150 / 300 mg (24h)','150-300 mg/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Cloridrato de Trazodona EMS','Trazodona','EMS','Comp. 50 / 100 mg; LP 150 mg','50-100 mg à noite','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Sonic','Trazodona','Eurofarma','50 / 100 mg','50-100 mg à noite','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Hemifumarato de Quetiapina EMS','Quetiapina','EMS','Comp. rev. 25 / 100 / 200 / 300 mg','300-800 mg/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Quet','Quetiapina','Eurofarma','25 / 100 / 200 mg','300-800 mg/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Quet XR','Quetiapina','Eurofarma','Liberação prolongada','300-800 mg/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Risperidona EMS','Risperidona','EMS','Comp. rev. 1 / 2 / 3 mg','1-6 mg/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Riss','Risperidona','Eurofarma','1 / 2 / 3 mg','1-6 mg/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Clonazepam EMS','Clonazepam','EMS','Comp. 0,5 / 2 mg; gotas','0,5-4 mg/dia','Psiquiatria',true,'EMS',true,'preta','azul_b'),
('Clonazepam Eurofarma','Clonazepam','Eurofarma','0,5 / 2 mg; gotas','0,5-4 mg/dia','Psiquiatria',true,'Eurofarma',true,'preta','azul_b'),
('Alprazolam EMS','Alprazolam','EMS','Comp. 0,25 / 0,5 / 1 / 2 mg','0,25-4 mg/dia','Psiquiatria',true,'EMS',true,'preta','azul_b'),
('Alprazolam Eurofarma','Alprazolam','Eurofarma','0,25 / 0,5 / 1 / 2 mg','0,25-4 mg/dia','Psiquiatria',true,'Eurofarma',true,'preta','azul_b'),
('Zolpidem EMS','Zolpidem','EMS','Comp. rev. 10 mg','10 mg à noite','Psiquiatria',true,'EMS',true,'preta','azul_b'),
('Zolpidem Eurofarma','Zolpidem','Eurofarma','10 mg','10 mg à noite','Psiquiatria',true,'Eurofarma',true,'preta','azul_b'),
('Cloridrato de Amitriptilina EMS','Amitriptilina','EMS','Comp. rev. 25 / 75 mg','25-150 mg/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Amytril','Amitriptilina','Eurofarma','25 / 75 mg','25-150 mg/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Cloridrato de Nortriptilina EMS','Nortriptilina','EMS','Cáps. 10 / 25 / 50 / 75 mg','25-150 mg/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Pamelor','Nortriptilina','Eurofarma','10 / 25 / 50 / 75 mg','25-150 mg/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Cloridrato de Duloxetina EMS','Duloxetina','EMS','Cáps. LP 30 / 60 mg','30-120 mg/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Dulotex','Duloxetina','Eurofarma','30 / 60 mg','30-120 mg/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Carbonato de Lítio EMS','Lítio','EMS','Comp. 300 mg','900-1800 mg/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Divalproato de Sódio EMS','Ácido valproico','EMS','Comp. LP 250 / 500 mg','500-2000 mg/dia','Psiquiatria',true,'EMS',true,'vermelha','branca_comum'),
('Torval CR','Ácido valproico','Eurofarma','250 / 500 mg LP','500-2000 mg/dia','Psiquiatria',true,'Eurofarma',true,'vermelha','branca_comum'),
('Lamotrigina EMS','Lamotrigina','EMS','Comp. 25 / 50 / 100 mg','25-200 mg/dia','Neurologia',true,'EMS',true,'vermelha','branca_comum'),
('Lamitor','Lamotrigina','Eurofarma','25 / 50 / 100 mg','25-200 mg/dia','Neurologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Topiramato EMS','Topiramato','EMS','Comp. rev. 25 / 50 / 100 mg','25-200 mg/dia','Neurologia',true,'EMS',true,'vermelha','branca_comum'),
('Topiramato Eurofarma','Topiramato','Eurofarma','25 / 50 / 100 mg','25-200 mg/dia','Neurologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Oxcarbazepina EMS','Oxcarbazepina','EMS','Comp. rev. 300 / 600 mg','600-2400 mg/dia','Neurologia',true,'EMS',true,'vermelha','branca_comum'),
('Oxcarbazepina Eurofarma','Oxcarbazepina','Eurofarma','300 / 600 mg','600-2400 mg/dia','Neurologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Levetiracetam EMS','Levetiracetam','EMS','Comp. rev. 250 / 500 / 750 / 1000 mg','1000-3000 mg/dia','Neurologia',true,'EMS',true,'vermelha','branca_comum'),
('Levetiracetam Eurofarma','Levetiracetam','Eurofarma','500 / 1000 mg','1000-3000 mg/dia','Neurologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Pregabalina EMS','Pregabalina','EMS','Cáps. 25 / 50 / 75 / 150 mg','75-600 mg/dia','Neurologia',true,'EMS',true,'vermelha','branca_comum'),
('Pregabid','Pregabalina','Eurofarma','75 / 150 mg','75-600 mg/dia','Neurologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Gabapentina EMS','Gabapentina','EMS','Cáps. 300 / 400 mg','300-3600 mg/dia','Neurologia',true,'EMS',true,'vermelha','branca_comum'),
('Gabaneurin','Gabapentina','Eurofarma','300 / 400 mg','300-3600 mg/dia','Neurologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Amoxicilina EMS','Amoxicilina','EMS','Cáps. 500 mg; susp.','500 mg 8/8h','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Amoxicilina Eurofarma','Amoxicilina','Eurofarma','500 mg; susp.','500 mg 8/8h','Antibióticos/Infectologia',true,'Eurofarma',true,'vermelha','antimicrobiano'),
('Amoxicilina + Clavulanato EMS','Amoxicilina + Clavulanato','EMS','500+125; 875+125 mg','875+125 mg 12/12h','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Amoxicilina + Clavulanato Eurofarma','Amoxicilina + Clavulanato','Eurofarma','500+125; 875+125 mg','875+125 mg 12/12h','Antibióticos/Infectologia',true,'Eurofarma',true,'vermelha','antimicrobiano'),
('Azitromicina EMS','Azitromicina','EMS','Comp. 500 mg; susp.','500 mg 1x/dia por 3-5 dias','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Azitromicina Eurofarma','Azitromicina','Eurofarma','500 mg; susp.','500 mg 1x/dia por 3-5 dias','Antibióticos/Infectologia',true,'Eurofarma',true,'vermelha','antimicrobiano'),
('Cefalexina EMS','Cefalexina','EMS','Cáps. 500 mg; susp.','500 mg 6/6h','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Cefalexina Eurofarma','Cefalexina','Eurofarma','500 mg; susp.','500 mg 6/6h','Antibióticos/Infectologia',true,'Eurofarma',true,'vermelha','antimicrobiano'),
('Cefadroxila EMS','Cefadroxila','EMS','Cáps. 500 mg','500 mg 12/12h','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Ciprofloxacino EMS','Ciprofloxacino','EMS','Comp. rev. 250 / 500 mg','500 mg 12/12h','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Ciprofloxacino Eurofarma','Ciprofloxacino','Eurofarma','250 / 500 mg','500 mg 12/12h','Antibióticos/Infectologia',true,'Eurofarma',true,'vermelha','antimicrobiano'),
('Levofloxacino EMS','Levofloxacino','EMS','Comp. rev. 500 / 750 mg','500-750 mg 1x/dia','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Levofloxacino Eurofarma','Levofloxacino','Eurofarma','500 / 750 mg','500-750 mg 1x/dia','Antibióticos/Infectologia',true,'Eurofarma',true,'vermelha','antimicrobiano'),
('Sulfametoxazol + Trimetoprima EMS','Sulfametoxazol + Trimetoprima','EMS','400+80 / 800+160 mg','800+160 mg 12/12h','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Metronidazol EMS','Metronidazol','EMS','Comp. 250 / 400 mg','400 mg 8/8h','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Metronidazol Eurofarma','Metronidazol','Eurofarma','250 / 400 mg','400 mg 8/8h','Antibióticos/Infectologia',true,'Eurofarma',true,'vermelha','antimicrobiano'),
('Nitrofurantoína EMS','Nitrofurantoína','EMS','Cáps. 100 mg','100 mg 6/6h','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Doxiciclina EMS','Doxiciclina','EMS','Cáps. 100 mg','100 mg 12/12h','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Claritromicina EMS','Claritromicina','EMS','Comp. rev. 250 / 500 mg','500 mg 12/12h','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Claritromicina Eurofarma','Claritromicina','Eurofarma','250 / 500 mg','500 mg 12/12h','Antibióticos/Infectologia',true,'Eurofarma',true,'vermelha','antimicrobiano'),
('Nistatina EMS','Nistatina','EMS','Susp. oral 100.000 UI/mL','5 mL 4x/dia','Antibióticos/Infectologia',true,'EMS',true,'vermelha','antimicrobiano'),
('Fluconazol EMS','Fluconazol','EMS','Cáps. 150 mg','150 mg dose única','Antibióticos/Infectologia',true,'EMS',true,'livre','branca_comum'),
('Fluconazol Eurofarma','Fluconazol','Eurofarma','150 mg','150 mg dose única','Antibióticos/Infectologia',true,'Eurofarma',true,'livre','branca_comum'),
('Aciclovir EMS','Aciclovir','EMS','Comp. 200 / 400 mg; creme','200-400 mg 5x/dia','Antibióticos/Infectologia',true,'EMS',true,'livre','branca_comum'),
('Omeprazol EMS','Omeprazol','EMS','Cáps. 10 / 20 / 40 mg','20-40 mg 1x/dia','Gastroenterologia',true,'EMS',true,'livre','branca_comum'),
('Omeprazol Eurofarma','Omeprazol','Eurofarma','10 / 20 / 40 mg','20-40 mg 1x/dia','Gastroenterologia',true,'Eurofarma',true,'livre','branca_comum'),
('Pantoprazol EMS','Pantoprazol','EMS','Comp. rev. 20 / 40 mg','40 mg 1x/dia','Gastroenterologia',true,'EMS',true,'livre','branca_comum'),
('Pantoprazol Eurofarma','Pantoprazol','Eurofarma','20 / 40 mg','40 mg 1x/dia','Gastroenterologia',true,'Eurofarma',true,'livre','branca_comum'),
('Esomeprazol EMS','Esomeprazol','EMS','Comp. 20 / 40 mg','20-40 mg 1x/dia','Gastroenterologia',true,'EMS',true,'livre','branca_comum'),
('Esomeprazol Eurofarma','Esomeprazol','Eurofarma','20 / 40 mg','20-40 mg 1x/dia','Gastroenterologia',true,'Eurofarma',true,'livre','branca_comum'),
('Ranitidina EMS','Ranitidina','EMS','Comp. 150 mg','150 mg 12/12h','Gastroenterologia',true,'EMS',true,'livre','branca_comum'),
('Domperidona EMS','Domperidona','EMS','Comp. 10 mg','10 mg 3x/dia','Gastroenterologia',true,'EMS',true,'livre','branca_comum'),
('Domperidona Eurofarma','Domperidona','Eurofarma','10 mg','10 mg 3x/dia','Gastroenterologia',true,'Eurofarma',true,'livre','branca_comum'),
('Bromoprida EMS','Bromoprida','EMS','Cáps. 10 mg; gotas','10 mg 3x/dia','Gastroenterologia',true,'EMS',true,'livre','branca_comum'),
('Ondansetrona EMS','Ondansetrona','EMS','Comp. 4 / 8 mg','4-8 mg 8/8h','Gastroenterologia',true,'EMS',true,'livre','branca_comum'),
('Vonau Flash','Ondansetrona','Eurofarma','ODT 4 / 8 mg','4-8 mg 8/8h','Gastroenterologia',true,'Eurofarma',true,'livre','branca_comum'),
('Simeticona EMS','Simeticona','EMS','Comp. 40 mg; gotas','40-80 mg após refeições','Gastroenterologia',true,'EMS',true,'livre','branca_comum'),
('Simeticona Eurofarma','Simeticona','Eurofarma','40 mg; gotas','40-80 mg após refeições','Gastroenterologia',true,'Eurofarma',true,'livre','branca_comum'),
('Loperamida EMS','Loperamida','EMS','Cáps. 2 mg','2 mg após cada evacuação','Gastroenterologia',true,'EMS',true,'livre','branca_comum'),
('Racecadotrila EMS','Racecadotrila','EMS','Cáps. 100 mg','100 mg 8/8h','Gastroenterologia',true,'EMS',true,'livre','branca_comum'),
('Tiorfan','Racecadotrila','Eurofarma','100 mg; sachês','100 mg 8/8h','Gastroenterologia',true,'Eurofarma',true,'livre','branca_comum'),
('Salbutamol EMS','Salbutamol','EMS','Aerosol 100 mcg/dose','1-2 puffs 4-6x/dia','Pneumologia/Alergologia',true,'EMS',true,'livre','branca_comum'),
('Aerojet','Salbutamol','Eurofarma','100 mcg/dose','1-2 puffs 4-6x/dia','Pneumologia/Alergologia',true,'Eurofarma',true,'livre','branca_comum'),
('Fenoterol EMS','Fenoterol','EMS','Sol. inal. 5 mg/mL','10-20 gotas NBZ','Pneumologia/Alergologia',true,'EMS',true,'livre','branca_comum'),
('Ipratrópio EMS','Ipratrópio','EMS','Sol. inal. 0,25 mg/mL','20-40 gotas NBZ','Pneumologia/Alergologia',true,'EMS',true,'livre','branca_comum'),
('Budesonida EMS','Budesonida','EMS','Aerosol 100 / 200 mcg','200-800 mcg/dia','Pneumologia/Alergologia',true,'EMS',true,'livre','branca_comum'),
('Busonid','Budesonida','Eurofarma','100 / 200 mcg','200-800 mcg/dia','Pneumologia/Alergologia',true,'Eurofarma',true,'livre','branca_comum'),
('Formoterol + Budesonida EMS','Formoterol + Budesonida','EMS','Cáps. inal.; aerosol','1-2 inal. 12/12h','Pneumologia/Alergologia',true,'EMS',true,'livre','branca_comum'),
('Alenia','Formoterol + Budesonida','Eurofarma','6+200 / 12+400 mcg','1-2 inal. 12/12h','Pneumologia/Alergologia',true,'Eurofarma',true,'livre','branca_comum'),
('Loratadina EMS','Loratadina','EMS','Comp. 10 mg; xarope','10 mg 1x/dia','Pneumologia/Alergologia',true,'EMS',true,'livre','branca_comum'),
('Loratadina Eurofarma','Loratadina','Eurofarma','10 mg; xarope','10 mg 1x/dia','Pneumologia/Alergologia',true,'Eurofarma',true,'livre','branca_comum'),
('Desloratadina EMS','Desloratadina','EMS','Comp. 5 mg; xarope','5 mg 1x/dia','Pneumologia/Alergologia',true,'EMS',true,'livre','branca_comum'),
('Desloratadina Eurofarma','Desloratadina','Eurofarma','5 mg; xarope','5 mg 1x/dia','Pneumologia/Alergologia',true,'Eurofarma',true,'livre','branca_comum'),
('Fexofenadina EMS','Fexofenadina','EMS','Comp. 60 / 120 / 180 mg','120-180 mg 1x/dia','Pneumologia/Alergologia',true,'EMS',true,'livre','branca_comum'),
('Fexofenadina Eurofarma','Fexofenadina','Eurofarma','120 / 180 mg','120-180 mg 1x/dia','Pneumologia/Alergologia',true,'Eurofarma',true,'livre','branca_comum'),
('Cetirizina EMS','Cetirizina','EMS','Comp. 10 mg','10 mg 1x/dia','Pneumologia/Alergologia',true,'EMS',true,'livre','branca_comum'),
('Cetirizina Eurofarma','Cetirizina','Eurofarma','10 mg','10 mg 1x/dia','Pneumologia/Alergologia',true,'Eurofarma',true,'livre','branca_comum'),
('Prednisolona EMS','Prednisolona','EMS','Sol. oral 3 / 11 mg/mL','1-2 mg/kg/dia','Pneumologia/Alergologia',true,'EMS',true,'vermelha','branca_comum'),
('Prednisolona Eurofarma','Prednisolona','Eurofarma','3 / 11 mg/mL','1-2 mg/kg/dia','Pneumologia/Alergologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Prednisona EMS','Prednisona','EMS','Comp. 5 / 20 / 40 mg','5-60 mg/dia','Pneumologia/Alergologia',true,'EMS',true,'vermelha','branca_comum'),
('Prednisona Eurofarma','Prednisona','Eurofarma','5 / 20 / 40 mg','5-60 mg/dia','Pneumologia/Alergologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Etinilestradiol + Gestodeno EMS','Etinilestradiol + Gestodeno','EMS','0,02+0,075 / 0,03+0,075 mg','1 comp./dia por 21 dias','Ginecologia',true,'EMS',true,'vermelha','branca_comum'),
('Level','Levonorgestrel + Etinilestradiol','Eurofarma','0,15+0,03 mg','1 comp./dia por 21 dias','Ginecologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Ciclo 21 EMS','Levonorgestrel + Etinilestradiol','EMS','0,15+0,03 mg','1 comp./dia por 21 dias','Ginecologia',true,'EMS',true,'vermelha','branca_comum'),
('Selene','Ciproterona + Etinilestradiol','Eurofarma','2+0,035 mg','1 comp./dia por 21 dias','Ginecologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Drospirenona + Etinilestradiol EMS','Drospirenona + Etinilestradiol','EMS','3+0,03 / 3+0,02 mg','1 comp./dia','Ginecologia',true,'EMS',true,'vermelha','branca_comum'),
('Iumi','Drospirenona + Etinilestradiol','Eurofarma','3+0,02 mg','1 comp./dia','Ginecologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Levonorgestrel 1,5 mg EMS','Levonorgestrel','EMS','Comp. 1,5 mg','Dose única','Ginecologia',true,'EMS',true,'vermelha','branca_comum'),
('Pozato','Levonorgestrel','Eurofarma','1,5 mg','Dose única','Ginecologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Ácido Fólico EMS','Ácido fólico','EMS','Comp. 5 mg','5 mg/dia','Ginecologia',true,'EMS',true,'livre','branca_comum'),
('Sulfato Ferroso EMS','Sulfato ferroso','EMS','Comp. 40 mg Fe','40-200 mg Fe/dia','Ginecologia',true,'EMS',true,'livre','branca_comum'),
('Noretisterona EMS','Noretisterona','EMS','Comp. 10 mg','10 mg 2x/dia','Ginecologia',true,'EMS',true,'vermelha','branca_comum'),
('Primosiston','Noretisterona + Estradiol','Eurofarma','10+2 mg','1 comp. 8/8h por 10 dias','Ginecologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Dipirona EMS','Dipirona','EMS','Comp. 500 mg; gotas','500-1000 mg 6/6h','Analgesia/Reumatologia',true,'EMS',true,'livre','branca_comum'),
('Dipirona Eurofarma','Dipirona','Eurofarma','500 mg; gotas','500-1000 mg 6/6h','Analgesia/Reumatologia',true,'Eurofarma',true,'livre','branca_comum'),
('Paracetamol EMS','Paracetamol','EMS','Comp. 500 / 750 mg; gotas','500-1000 mg 6/6h','Analgesia/Reumatologia',true,'EMS',true,'livre','branca_comum'),
('Paracetamol Eurofarma','Paracetamol','Eurofarma','500 / 750 mg','500-1000 mg 6/6h','Analgesia/Reumatologia',true,'Eurofarma',true,'livre','branca_comum'),
('Ibuprofeno EMS','Ibuprofeno','EMS','Comp. 200-600 mg','400-600 mg 6/6h','Analgesia/Reumatologia',true,'EMS',true,'livre','branca_comum'),
('Ibuprofeno Eurofarma','Ibuprofeno','Eurofarma','200 / 400 / 600 mg','400-600 mg 6/6h','Analgesia/Reumatologia',true,'Eurofarma',true,'livre','branca_comum'),
('Nimesulida EMS','Nimesulida','EMS','Comp. 100 mg; gotas','100 mg 12/12h','Analgesia/Reumatologia',true,'EMS',true,'livre','branca_comum'),
('Nimesulida Eurofarma','Nimesulida','Eurofarma','100 mg; gotas','100 mg 12/12h','Analgesia/Reumatologia',true,'Eurofarma',true,'livre','branca_comum'),
('Naproxeno EMS','Naproxeno','EMS','Comp. 250 / 500 mg','500 mg 12/12h','Analgesia/Reumatologia',true,'EMS',true,'livre','branca_comum'),
('Diclofenaco Sódico EMS','Diclofenaco sódico','EMS','Comp. 50 mg','50 mg 8/8h','Analgesia/Reumatologia',true,'EMS',true,'livre','branca_comum'),
('Diclofenaco Potássico EMS','Diclofenaco potássico','EMS','Comp. 50 mg; gotas','50 mg 8/8h','Analgesia/Reumatologia',true,'EMS',true,'livre','branca_comum'),
('Meloxicam EMS','Meloxicam','EMS','Comp. 7,5 / 15 mg','7,5-15 mg 1x/dia','Analgesia/Reumatologia',true,'EMS',true,'vermelha','branca_comum'),
('Movatec','Meloxicam','Eurofarma','7,5 / 15 mg','7,5-15 mg 1x/dia','Analgesia/Reumatologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Celecoxibe EMS','Celecoxibe','EMS','Cáps. 100 / 200 mg','200 mg 1-2x/dia','Analgesia/Reumatologia',true,'EMS',true,'vermelha','branca_comum'),
('Etoricoxibe EMS','Etoricoxibe','EMS','Comp. 60 / 90 / 120 mg','60-120 mg 1x/dia','Analgesia/Reumatologia',true,'EMS',true,'vermelha','branca_comum'),
('Ciclobenzaprina EMS','Ciclobenzaprina','EMS','Comp. 5 / 10 mg','5-10 mg 3x/dia','Analgesia/Reumatologia',true,'EMS',true,'vermelha','branca_comum'),
('Cloridrato de Tramadol EMS','Tramadol','EMS','Cáps. 50 mg; gotas','50-100 mg 6/6h','Analgesia/Reumatologia',true,'EMS',true,'vermelha_retencao','controle_especial'),
('Tramadon','Tramadol','Eurofarma','50 mg; gotas','50-100 mg 6/6h','Analgesia/Reumatologia',true,'Eurofarma',true,'vermelha_retencao','controle_especial'),
('Codeína + Paracetamol EMS','Codeína + Paracetamol','EMS','30+500 mg','1 comp. 6/6h','Analgesia/Reumatologia',true,'EMS',true,'vermelha_retencao','controle_especial'),
('Alopurinol EMS','Alopurinol','EMS','Comp. 100 / 300 mg','100-300 mg 1x/dia','Analgesia/Reumatologia',true,'EMS',true,'vermelha','branca_comum'),
('Colchicina EMS','Colchicina','EMS','Comp. 0,5 mg','0,5 mg 1-2x/dia','Analgesia/Reumatologia',true,'EMS',true,'vermelha','branca_comum'),
('Metotrexato EMS','Metotrexato','EMS','Comp. 2,5 mg','7,5-25 mg 1x/semana','Analgesia/Reumatologia',true,'EMS',true,'vermelha','branca_comum'),
('Cetoconazol EMS','Cetoconazol','EMS','Comp. 200 mg; xampu; creme','200 mg/dia','Dermatologia',true,'EMS',true,'vermelha','branca_comum'),
('Cetoconazol Eurofarma','Cetoconazol','Eurofarma','200 mg; xampu; creme','200 mg/dia','Dermatologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Isotretinoína EMS','Isotretinoína','EMS','Cáps. 10 / 20 mg','0,5-1 mg/kg/dia','Dermatologia',true,'EMS',true,'vermelha_retencao','controle_especial'),
('Isotretinoína Eurofarma','Isotretinoína','Eurofarma','10 / 20 mg','0,5-1 mg/kg/dia','Dermatologia',true,'Eurofarma',true,'vermelha_retencao','controle_especial'),
('Adapaleno EMS','Adapaleno','EMS','Gel 0,1% / 0,3%','1x/dia à noite','Dermatologia',true,'EMS',true,'livre','branca_comum'),
('Peróxido de Benzoíla EMS','Peróxido de benzoíla','EMS','Gel 2,5% / 5%','1-2x/dia','Dermatologia',true,'EMS',true,'livre','branca_comum'),
('Clindamicina tópica EMS','Clindamicina','EMS','Gel 1%; sol. 1%','2x/dia','Dermatologia',true,'EMS',true,'vermelha','branca_comum'),
('Ácido Salicílico EMS','Ácido salicílico','EMS','Loção 2%','1-2x/dia','Dermatologia',true,'EMS',true,'livre','branca_comum'),
('Minoxidil EMS','Minoxidil','EMS','Sol. tópica 5%','1 mL 2x/dia','Dermatologia',true,'EMS',true,'livre','branca_comum'),
('Finasterida EMS','Finasterida','EMS','Comp. 1 / 5 mg','1 mg/dia (alopecia)','Dermatologia',true,'EMS',true,'vermelha','branca_comum'),
('Terbinafina EMS','Terbinafina','EMS','Comp. 250 mg; creme','250 mg/dia','Dermatologia',true,'EMS',true,'vermelha','branca_comum'),
('Terbinafina Eurofarma','Terbinafina','Eurofarma','250 mg; creme','250 mg/dia','Dermatologia',true,'Eurofarma',true,'vermelha','branca_comum'),
('Hidrocortisona creme EMS','Hidrocortisona','EMS','Creme 1%','2-3x/dia','Dermatologia',true,'EMS',true,'livre','branca_comum'),
('Betametasona creme EMS','Betametasona','EMS','Creme 0,05% / 0,1%','1-2x/dia','Dermatologia',true,'EMS',true,'vermelha','branca_comum'),
('Dexametasona creme EMS','Dexametasona','EMS','Creme 0,1%','2x/dia','Dermatologia',true,'EMS',true,'vermelha','branca_comum'),
('Permetrina EMS','Permetrina','EMS','Loção 1% / 5%','Aplicação única, repetir em 7 dias','Dermatologia',true,'EMS',true,'livre','branca_comum'),
('Ivermectina EMS','Ivermectina','EMS','Comp. 6 mg','200 mcg/kg dose única','Dermatologia',true,'EMS',true,'vermelha','branca_comum'),
('Ivermectina Eurofarma','Ivermectina','Eurofarma','6 mg','200 mcg/kg dose única','Dermatologia',true,'Eurofarma',true,'vermelha','branca_comum')
)
INSERT INTO public.medications (nome_comercial, principio_ativo, laboratorio, apresentacao, posologia_referencia, classe_terapeutica, is_parceiro, parceiro_nome, ativo, tarja, tipo_receita)
SELECT n.nome_comercial, n.principio_ativo, n.laboratorio, n.apresentacao, n.posologia_referencia, n.classe_terapeutica, n.is_parceiro, n.parceiro_nome, n.ativo, n.tarja, n.tipo_receita
FROM new_meds n
WHERE NOT EXISTS (
  SELECT 1 FROM public.medications m
  WHERE lower(m.nome_comercial) = lower(n.nome_comercial)
);