-- =====================================================================
-- MindMed — Parceria EMS & Eurofarma
-- =====================================================================

UPDATE public.medications SET laboratorio='Sanofi Medley', is_parceiro=false, parceiro_nome=NULL WHERE nome_comercial='Allegra';
UPDATE public.medications SET laboratorio='GSK', is_parceiro=false, parceiro_nome=NULL WHERE nome_comercial='Amoxil';
UPDATE public.medications SET laboratorio='Merck', is_parceiro=false, parceiro_nome=NULL WHERE nome_comercial='Glifage XR';
UPDATE public.medications SET laboratorio='Theraskin', is_parceiro=false, parceiro_nome=NULL WHERE nome_comercial='Hixizine';
UPDATE public.medications SET laboratorio='Bagó/ABL', is_parceiro=false, parceiro_nome=NULL WHERE nome_comercial='Keflex';
UPDATE public.medications SET laboratorio='Bayer', is_parceiro=false, parceiro_nome=NULL WHERE nome_comercial='Naprosyn';
UPDATE public.medications SET laboratorio='Takeda', is_parceiro=false, parceiro_nome=NULL WHERE nome_comercial='Pantozol';
UPDATE public.medications SET laboratorio='Gedeon Richter/Aché', is_parceiro=false, parceiro_nome=NULL WHERE nome_comercial='Postinor';
UPDATE public.medications SET laboratorio='Mantecorp (Hypera)', is_parceiro=false, parceiro_nome=NULL WHERE nome_comercial='Predsim';
UPDATE public.medications SET laboratorio='Biolab Sanus', is_parceiro=false, parceiro_nome=NULL WHERE nome_comercial='Tapazol';

UPDATE public.medications SET laboratorio='Neo Química (Hypera)', principio_ativo='Dexclorfeniramina',
  classe_terapeutica='Anti-histamínico de 1ª geração', is_parceiro=false, parceiro_nome=NULL
WHERE nome_comercial='Histamin';

UPDATE public.medications SET laboratorio='EMS', parceiro_nome='EMS' WHERE nome_comercial='Folifolin';

UPDATE public.medications SET ativo=false WHERE nome_comercial IN ('Cefaclor Eurofarma','Label','Floxstat','Cefepima');

UPDATE public.medications SET nome_comercial='Cloridrato de Trazodona EMS' WHERE nome_comercial='Trazodone EMS';
UPDATE public.medications SET nome_comercial='Vitafer (Sulfato Ferroso) EMS' WHERE nome_comercial='Sulfato Ferroso EMS';

UPDATE public.medications SET
  classe_terapeutica='Análogo de GLP-1 — Antidiabético',
  indicacoes='Diabetes mellitus tipo 2 (indicação aprovada Anvisa 05/2026). Primeira caneta de semaglutida nacional (EMS), ~30% mais barata que a referência.',
  cid10_relacionados='{E11,E11.9}'::text[]
WHERE nome_comercial='Ozivy';

UPDATE public.medications SET tipo_receita='controle_especial'
WHERE tipo_receita='branca_comum' AND (
  principio_ativo ILIKE ANY(ARRAY['%trazodona%','%duloxetina%','%venlafaxina%','%bupropiona%','%mirtazapina%','%escitalopram%','%sertralina%','%fluoxetina%',
    '%aripiprazol%','%haloperidol%','%risperidona%','%quetiapina%','%olanzapina%','%lamotrigina%','%carbamazepina%','%divalproato%','%valproico%',
    '%gabapentina%','%pregabalina%','%topiramato%','%isotretinoína%','%isotretinoina%'])
);

-- PARTE 2 — NOVOS MEDICAMENTOS EMS
INSERT INTO public.medications (nome_comercial, principio_ativo, laboratorio, apresentacao, concentracao, forma_farmaceutica, via_administracao, classe_terapeutica, tarja, tipo_receita, posologia_referencia, indicacoes, cid10_relacionados, is_parceiro, parceiro_nome)
SELECT v.* FROM (VALUES
('Besilato de Anlodipino EMS','Besilato de Anlodipino','EMS','Comprimido 5 e 10 mg','5-10mg','Comprimido','Oral','Anti-hipertensivo - BCC','vermelha','branca_comum','5-10 mg 1x/dia','Hipertensão arterial, angina','{I10,I20}'::text[],true,'EMS'),
('Espironolactona EMS','Espironolactona','EMS','Comprimido 25, 50 e 100 mg','25-100mg','Comprimido','Oral','Diurético poupador de K+','vermelha','branca_comum','25-100 mg/dia','ICC, HAS resistente, cirrose','{I50,I10,K70}'::text[],true,'EMS'),
('Atorvastatina Cálcica EMS','Atorvastatina Cálcica','EMS','Comprimido revestido 10, 20, 40 e 80 mg','10-80mg','Comprimido','Oral','Hipolipemiante - Estatina','vermelha','branca_comum','10-80 mg 1x/dia','Dislipidemia','{E78.5}'::text[],true,'EMS'),
('Rosuvastatina Cálcica EMS','Rosuvastatina Cálcica','EMS','Comprimido revestido 5, 10, 20 e 40 mg','5-40mg','Comprimido','Oral','Hipolipemiante - Estatina','vermelha','branca_comum','10-20 mg 1x/dia','Dislipidemia','{E78.0}'::text[],true,'EMS'),
('Bissulfato de Clopidogrel EMS','Clopidogrel','EMS','Comprimido revestido 75 mg','75mg','Comprimido','Oral','Antiagregante plaquetário','vermelha','branca_comum','75 mg 1x/dia','SCA, AVC isquêmico, doença coronariana','{I25.9,I21,I63}'::text[],true,'EMS'),
('Glibenclamida EMS','Glibenclamida','EMS','Comprimido 5 mg, caixa 30','5mg','Comprimido','Oral','Antidiabético - Sulfonilureia','vermelha','branca_comum','2,5-5 mg 1x/dia no café; máx. 20 mg/dia','Diabetes tipo 2','{E11.9}'::text[],true,'EMS'),
('Gliclazida EMS','Gliclazida','EMS','Comprimido liberação prolongada 30 e 60 mg','30-60mg','Comprimido LP','Oral','Antidiabético - Sulfonilureia','vermelha','branca_comum','30-120 mg 1x/dia no café da manhã','Diabetes tipo 2','{E11.9}'::text[],true,'EMS'),
('Dapagliflozina EMS','Dapagliflozina','EMS','Comprimido revestido 10 mg, caixa 30','10mg','Comprimido','Oral','Antidiabético - iSGLT2','vermelha','branca_comum','10 mg 1x/dia','DM2, ICC, DRC','{E11,I50,N18}'::text[],true,'EMS'),
('Empagliflozina EMS','Empagliflozina','EMS','Comprimido revestido 10 e 25 mg, caixa 30','10-25mg','Comprimido','Oral','Antidiabético - iSGLT2','vermelha','branca_comum','10-25 mg 1x/dia','DM2, ICC','{E11,I50}'::text[],true,'EMS'),
('Fosfato de Sitagliptina EMS','Sitagliptina','EMS','Comprimido revestido 25, 50 e 100 mg','25-100mg','Comprimido','Oral','Antidiabético - iDPP4','vermelha','branca_comum','100 mg 1x/dia','Diabetes tipo 2','{E11}'::text[],true,'EMS'),
('Olire','Liraglutida','EMS','Caneta 6 mg/mL, 3 mL (18 mg)','6mg/mL','Solução injetável (caneta)','Subcutânea','Análogo de GLP-1 — Obesidade','vermelha','branca_comum','Titulação semanal de 0,6 mg/dia até 3 mg/dia SC','Obesidade e sobrepeso com comorbidades. 1ª caneta emagrecedora nacional (2025)','{E66}'::text[],true,'EMS'),
('Lirux','Liraglutida','EMS','Caneta 6 mg/mL, 3 mL (18 mg)','6mg/mL','Solução injetável (caneta)','Subcutânea','Análogo de GLP-1 — Antidiabético','vermelha','branca_comum','1,2-1,8 mg SC 1x/dia','Diabetes tipo 2','{E11}'::text[],true,'EMS'),
('Cloridrato de Sertralina EMS','Sertralina','EMS','Comprimido revestido 50 e 100 mg','50-100mg','Comprimido','Oral','Antidepressivo - ISRS','vermelha','controle_especial','50 mg 1x/dia; máx. 200 mg/dia','Depressão, TOC, pânico, TAG','{F32,F42,F41}'::text[],true,'EMS'),
('Oxalato de Escitalopram EMS','Escitalopram','EMS','Comprimido revestido 10, 15 e 20 mg','10-20mg','Comprimido','Oral','Antidepressivo - ISRS','vermelha','controle_especial','10 mg 1x/dia; máx. 20 mg/dia','Depressão e ansiedade','{F32,F41}'::text[],true,'EMS'),
('Cloridrato de Fluoxetina EMS','Fluoxetina','EMS','Cápsula/comprimido 20 mg','20mg','Cápsula','Oral','Antidepressivo - ISRS','vermelha','controle_especial','20 mg pela manhã; máx. 80 mg/dia','Depressão, TOC, bulimia','{F32,F42}'::text[],true,'EMS'),
('Cloridrato de Paroxetina EMS','Paroxetina','EMS','Comprimido revestido 20 mg','20mg','Comprimido','Oral','Antidepressivo - ISRS','vermelha','controle_especial','20 mg 1x/dia pela manhã; máx. 50 mg/dia','Depressão, ansiedade, pânico','{F32,F41}'::text[],true,'EMS'),
('Cloridrato de Venlafaxina EMS','Venlafaxina','EMS','Cápsula liberação prolongada 37,5, 75 e 150 mg','37,5-150mg','Cápsula LP','Oral','Antidepressivo - IRSN','vermelha','controle_especial','75 mg 1x/dia; máx. 225 mg/dia','Depressão, TAG','{F32,F41.1}'::text[],true,'EMS'),
('Succinato de Desvenlafaxina EMS','Desvenlafaxina','EMS','Comprimido liberação prolongada 50 e 100 mg','50-100mg','Comprimido LP','Oral','Antidepressivo - IRSN','vermelha','controle_especial','50 mg 1x/dia; máx. 200 mg/dia','Depressão','{F32}'::text[],true,'EMS'),
('Cloridrato de Bupropiona EMS','Bupropiona','EMS','Comprimido liberação prolongada 150 mg; XL 300 mg','150-300mg','Comprimido LP','Oral','Antidepressivo atípico','vermelha','controle_especial','150-300 mg/dia (XL: 1x/dia pela manhã)','Depressão, cessação do tabagismo','{F32,F17}'::text[],true,'EMS'),
('Hemifumarato de Quetiapina EMS','Quetiapina','EMS','Comprimido revestido 25, 100, 200 e 300 mg','25-300mg','Comprimido','Oral','Antipsicótico atípico','vermelha','controle_especial','Titulação; usual 300-800 mg/dia','Esquizofrenia, transtorno bipolar','{F20,F31}'::text[],true,'EMS'),
('Risperidona EMS','Risperidona','EMS','Comprimido 1, 2 e 3 mg; solução oral 1 mg/mL','1-3mg','Comprimido','Oral','Antipsicótico atípico','vermelha','controle_especial','1-6 mg/dia','Esquizofrenia, agitação','{F20}'::text[],true,'EMS'),
('Clonazepam EMS','Clonazepam','EMS','Comprimido 0,5 e 2 mg; gotas 2,5 mg/mL','0,5-2mg','Comprimido','Oral','Benzodiazepínico (B1)','preta','azul_b','0,5-2 mg/dia (ansiedade); até 20 mg/dia (epilepsia)','Ansiedade, convulsões','{F41.9,G40.9}'::text[],true,'EMS'),
('Alprazolam EMS','Alprazolam','EMS','Comprimido 0,25, 0,5, 1 e 2 mg','0,25-2mg','Comprimido','Oral','Benzodiazepínico (B1)','preta','azul_b','0,5-4 mg/dia divididos','Transtornos de ansiedade','{F41.1}'::text[],true,'EMS'),
('Hemitartarato de Zolpidem EMS','Zolpidem','EMS','Comprimido revestido 10 mg (incl. sublingual)','10mg','Comprimido','Oral','Hipnótico não-benzodiazepínico (B1)','preta','azul_b','10 mg ao deitar (5 mg SL em idosos)','Insônia','{G47.0}'::text[],true,'EMS'),
('Mirtazapina EMS','Mirtazapina','EMS','Comprimido revestido/orodispersível 15, 30 e 45 mg','15-45mg','Comprimido','Oral','Antidepressivo atípico','vermelha','controle_especial','15-45 mg à noite','Depressão, insônia','{F32,G47}'::text[],true,'EMS'),
('Gabapentina EMS','Gabapentina','EMS','Cápsula 300 e 400 mg','300-400mg','Cápsula','Oral','Anticonvulsivante','vermelha','controle_especial','900-1.800 mg/dia em 3 tomadas','Dor neuropática, epilepsia','{G62,G40}'::text[],true,'EMS'),
('Pregabalina EMS','Pregabalina','EMS','Cápsula 75 e 150 mg (linha 50-300 mg)','75-150mg','Cápsula','Oral','Anticonvulsivante/Dor neuropática','vermelha','controle_especial','150-600 mg/dia em 2 tomadas','Dor neuropática, fibromialgia','{G62,M79.7}'::text[],true,'EMS'),
('Carbamazepina EMS','Carbamazepina','EMS','Comprimido 200 mg','200mg','Comprimido','Oral','Antiepiléptico','vermelha','controle_especial','400-1.200 mg/dia divididos','Epilepsia, neuralgia do trigêmeo','{G40,G50.0}'::text[],true,'EMS'),
('Divalproato de Sódio EMS','Divalproato de Sódio','EMS','Comprimido liberação prolongada 250 e 500 mg','250-500mg','Comprimido LP','Oral','Antiepiléptico/Estabilizador de humor','vermelha','controle_especial','500-1.500 mg/dia','Epilepsia, bipolar, enxaqueca','{G40,F31,G43}'::text[],true,'EMS'),
('Topiramato EMS','Topiramato','EMS','Comprimido revestido 25, 50 e 100 mg','25-100mg','Comprimido','Oral','Antiepiléptico','vermelha','controle_especial','50-200 mg/dia em 2 tomadas (enxaqueca: 100 mg/dia)','Epilepsia, profilaxia de enxaqueca','{G40,G43}'::text[],true,'EMS'),
('Levetiracetam EMS','Levetiracetam','EMS','Comprimido 250, 750 e 1.000 mg; solução 100 mg/mL','250-1000mg','Comprimido','Oral','Antiepiléptico','vermelha','controle_especial','500 mg 2x/dia; até 1.500 mg 2x/dia','Epilepsia','{G40}'::text[],true,'EMS'),
('Cloridrato de Amitriptilina EMS','Amitriptilina','EMS','Comprimido 25 e 75 mg','25-75mg','Comprimido','Oral','Antidepressivo tricíclico','vermelha','controle_especial','25-75 mg à noite (dor/enxaqueca); até 150 mg','Depressão, dor crônica, enxaqueca','{F32,G43,M79.7}'::text[],true,'EMS'),
('Cloridrato de Donepezila EMS','Donepezila','EMS','Comprimido revestido/ODT 5 e 10 mg','5-10mg','Comprimido','Oral','Anticolinesterásico','vermelha','controle_especial','5 mg/dia; 10 mg/dia após 4-6 semanas','Doença de Alzheimer','{G30,F03}'::text[],true,'EMS'),
('Cloridrato de Naratriptana EMS','Naratriptana','EMS','Comprimido 2,5 mg','2,5mg','Comprimido','Oral','Triptano','vermelha','branca_comum','2,5 mg; repetir após 4h se necessário (máx. 5 mg/dia)','Crise de enxaqueca','{G43}'::text[],true,'EMS'),
('Amoxicilina + Clavulanato de Potássio EMS','Amoxicilina + Clavulanato','EMS','Comprimido 500+125 e 875+125 mg; suspensão 400+57 mg/5 mL','875+125mg','Comprimido','Oral','Antibiótico - Penicilina + inibidor','vermelha','antimicrobiano','875+125 mg 12/12h por 7-10 dias','Sinusite, OMA, ITU, infecção respiratória','{J32,H66,N39.0,J20}'::text[],true,'EMS'),
('Cloridrato de Ciprofloxacino EMS','Ciprofloxacino','EMS','Comprimido revestido 500 mg','500mg','Comprimido','Oral','Antibiótico - Quinolona','vermelha','antimicrobiano','500 mg 12/12h por 7 dias','ITU, infecções gastrointestinais','{N39.0,A09.9}'::text[],true,'EMS'),
('Levofloxacino EMS','Levofloxacino','EMS','Comprimido revestido 500 e 750 mg','500-750mg','Comprimido','Oral','Antibiótico - Quinolona','vermelha','antimicrobiano','500-750 mg 1x/dia por 7-14 dias','Pneumonia, ITU complicada','{J18,N39.0}'::text[],true,'EMS'),
('Metronidazol EMS','Metronidazol','EMS','Comprimido revestido 250 e 400 mg','250-400mg','Comprimido','Oral','Antibacteriano/Antiprotozoário','vermelha','antimicrobiano','250-400 mg 8/8h por 7 dias','Infecções anaeróbias, giardíase, vaginose','{A07.1,N76.0}'::text[],true,'EMS'),
('Sulfametoxazol + Trimetoprima EMS','Sulfametoxazol + Trimetoprima','EMS','Comprimido 400+80 e 800+160 mg; suspensão oral','800+160mg','Comprimido','Oral','Antibiótico - Sulfa','vermelha','antimicrobiano','800+160 mg 12/12h por 7-10 dias','ITU, infecções respiratórias','{N39.0}'::text[],true,'EMS'),
('Nitrofurantoína EMS','Nitrofurantoína','EMS','Cápsula 100 mg, caixa 28','100mg','Cápsula','Oral','Antibiótico urinário','vermelha','antimicrobiano','100 mg 6/6h por 7-10 dias','ITU não complicada (1ª linha)','{N39.0}'::text[],true,'EMS'),
('Ceftriaxona EMS','Ceftriaxona','EMS','Pó para solução injetável IM/IV 500 mg e 1 g','500mg-1g','Injetável','IV/IM','Antibiótico - Cefalosporina 3ª geração','vermelha','antimicrobiano','1-2 g IV/IM 1x/dia','Pneumonia, meningite, pielonefrite','{J18,G00,N10}'::text[],true,'EMS'),
('Pantoprazol EMS','Pantoprazol','EMS','Comprimido liberação retardada 20 e 40 mg','20-40mg','Comprimido','Oral','Inibidor de bomba de prótons','vermelha','branca_comum','20-40 mg 1x/dia em jejum','DRGE, úlcera péptica','{K21.9,K25.9}'::text[],true,'EMS'),
('Esomeprazol Magnésico EMS','Esomeprazol','EMS','Comprimido 20 e 40 mg','20-40mg','Comprimido','Oral','Inibidor de bomba de prótons','vermelha','branca_comum','20-40 mg 1x/dia em jejum','DRGE','{K21}'::text[],true,'EMS'),
('Domperidona EMS','Domperidona','EMS','Comprimido 10 mg','10mg','Comprimido','Oral','Procinético','vermelha','branca_comum','10 mg 3x/dia antes das refeições','Náusea, vômito, dispepsia','{R11,K30}'::text[],true,'EMS'),
('Cloridrato de Metoclopramida EMS','Metoclopramida','EMS','Comprimido 10 mg; gotas','10mg','Comprimido','Oral','Antiemético','vermelha','branca_comum','10 mg até 3x/dia antes das refeições','Náuseas e vômitos','{R11}'::text[],true,'EMS'),
('Cloridrato de Ondansetrona EMS','Ondansetrona','EMS','Comprimido orodispersível 4 e 8 mg, caixa 10','4-8mg','Comprimido orodispersível','Oral','Antiemético 5HT3','vermelha','branca_comum','8 mg 8/8h a 12/12h','Náusea/vômito intensos','{R11}'::text[],true,'EMS'),
('Bromoprida EMS','Bromoprida','EMS','Cápsula 10 mg; gotas 4 mg/mL','10mg','Cápsula','Oral','Antiemético/Procinético','vermelha','branca_comum','10 mg 3x/dia','Náuseas, vômitos, dispepsia','{R11,K30}'::text[],true,'EMS'),
('Simeticona EMS','Simeticona','EMS','Comprimido 40 e 125 mg; gotas 75 mg/mL','40-125mg','Comprimido','Oral','Antiflatulento','livre','branca_comum','40-125 mg 3-4x/dia','Gases, distensão abdominal','{R14}'::text[],true,'EMS'),
('Budesonida EMS','Budesonida','EMS','Spray nasal 32 e 64 mcg/dose','32-64mcg','Spray nasal','Nasal','Corticosteroide nasal','vermelha','branca_comum','1-2 jatos por narina 1-2x/dia','Rinite alérgica','{J30}'::text[],true,'EMS'),
('Montelucaste de Sódio EMS','Montelucaste','EMS','Comprimido mastigável 4 e 5 mg; revestido 10 mg','4-10mg','Comprimido','Oral','Antileucotrieno','vermelha','branca_comum','10 mg 1x/dia à noite (4-5 mg pediátrico)','Asma, rinite alérgica','{J45,J30}'::text[],true,'EMS'),
('Desloratadina EMS','Desloratadina','EMS','Comprimido revestido 5 mg; xarope 0,5 mg/mL','5mg','Comprimido','Oral','Anti-histamínico','livre','branca_comum','5 mg 1x/dia','Rinite alérgica, urticária','{J30,L50}'::text[],true,'EMS'),
('Cloridrato de Fexofenadina EMS','Fexofenadina','EMS','Comprimido revestido 120 e 180 mg','120-180mg','Comprimido','Oral','Anti-histamínico não sedativo','livre','branca_comum','120-180 mg 1x/dia','Rinite alérgica, urticária','{J30.4,L50.9}'::text[],true,'EMS'),
('Alektos','Bilastina','EMS','Comprimido 20 mg','20mg','Comprimido','Oral','Anti-histamínico não sedativo','livre','branca_comum','20 mg 1x/dia','Rinite alérgica, urticária','{J30,L50}'::text[],true,'EMS'),
('Dicloridrato de Hidroxizina EMS','Hidroxizina','EMS','Comprimido 25 mg; xarope 2 mg/mL','25mg','Comprimido','Oral','Anti-histamínico','vermelha','branca_comum','25 mg 2-3x/dia','Prurido, urticária','{L29.9,L50.9}'::text[],true,'EMS'),
('Fosfato Sódico de Prednisolona EMS','Prednisolona','EMS','Solução oral 1 mg/mL e 3 mg/mL','1-3mg/mL','Solução oral','Oral','Corticosteroide','vermelha','branca_comum','5-60 mg/dia (pediátrico ~1 mg/kg/dia)','Processos alérgicos e inflamatórios','{J45.9,L20.9}'::text[],true,'EMS'),
('Prednisona EMS','Prednisona','EMS','Comprimido 5 e 20 mg','5-20mg','Comprimido','Oral','Corticosteroide','vermelha','branca_comum','5-60 mg/dia, dose única matinal','Doenças inflamatórias e autoimunes','{J45.9,M06.9}'::text[],true,'EMS'),
('Acetilcisteína EMS','Acetilcisteína','EMS','Xarope 20 e 40 mg/mL; granulado 200 e 600 mg','600mg','Xarope/Granulado','Oral','Mucolítico','livre','branca_comum','600 mg/dia por 5-10 dias','Tosse produtiva','{R05}'::text[],true,'EMS'),
('Cloridrato de Ambroxol EMS','Ambroxol','EMS','Xarope 30 mg/5 mL (adulto) e 15 mg/5 mL (pediátrico)','30mg/5mL','Xarope','Oral','Mucolítico','livre','branca_comum','30 mg 3x/dia','Tosse produtiva','{R05}'::text[],true,'EMS'),
('Sulfato de Salbutamol EMS','Salbutamol','EMS','Xarope 2 mg/5 mL','2mg/5mL','Xarope','Oral','Broncodilatador beta-2','vermelha','branca_comum','2-4 mg 3-4x/dia VO','Broncoespasmo, asma','{J45}'::text[],true,'EMS'),
('Drospirenona + Etinilestradiol EMS','Drospirenona + Etinilestradiol','EMS','Comprimido 3+0,03 mg (21/63) e 3+0,02 mg (24/72)','3+0,03mg','Comprimido','Oral','Contraceptivo combinado','vermelha','branca_comum','1 comp/dia; 21+7 ou 24+4','Contracepção hormonal','{Z30}'::text[],true,'EMS'),
('Acetato de Ciproterona + Etinilestradiol EMS','Ciproterona + Etinilestradiol','EMS','Comprimido revestido 2+0,035 mg, caixa 21','2+0,035mg','Comprimido','Oral','Contraceptivo combinado antiandrogênico','vermelha','branca_comum','1 comp/dia por 21 dias + 7 pausa','Acne hormonal, SOP, contracepção','{L70,E28.2,Z30}'::text[],true,'EMS'),
('Desogestrel EMS','Desogestrel','EMS','Comprimido 0,075 mg, caixa 28','75mcg','Comprimido','Oral','Contraceptivo progestágeno','vermelha','branca_comum','1 comp/dia contínuo, sem pausa','Contracepção (incl. amamentação)','{Z30}'::text[],true,'EMS'),
('Estradiol EMS','Estradiol','EMS','Comprimido 1 e 2 mg','1-2mg','Comprimido','Oral','Estrogênio - TRH','vermelha','branca_comum','1-2 mg 1x/dia','Terapia de reposição hormonal','{N95}'::text[],true,'EMS'),
('Estradiol + Acetato de Noretisterona EMS','Estradiol + Noretisterona','EMS','Comprimido revestido 2+1 mg, caixa 28','2+1mg','Comprimido','Oral','TRH combinada','vermelha','branca_comum','1 comp/dia contínuo','Terapia de reposição hormonal','{N95}'::text[],true,'EMS'),
('Tibolona EMS','Tibolona','EMS','Comprimido 1,25 e 2,5 mg','1,25-2,5mg','Comprimido','Oral','TRH - Esteroide sintético','vermelha','branca_comum','2,5 mg 1x/dia','Sintomas do climatério','{N95}'::text[],true,'EMS'),
('Nimesulida EMS','Nimesulida','EMS','Comprimido 100 mg; gotas; dispersível','100mg','Comprimido','Oral','AINE','vermelha','branca_comum','100 mg 12/12h após refeições','Dor e inflamação','{M79.1}'::text[],true,'EMS'),
('Diclofenaco Sódico EMS','Diclofenaco Sódico','EMS','Comprimido 50 mg; gel tópico','50mg','Comprimido','Oral','AINE','vermelha','branca_comum','50 mg 2-3x/dia após refeições','Dor e inflamação','{M79.1,M25.5}'::text[],true,'EMS'),
('Cetoprofeno EMS','Cetoprofeno','EMS','Comprimido 100 mg; cápsula LP 150 e 200 mg; gotas 20 mg/mL','100-200mg','Comprimido','Oral','AINE','vermelha','branca_comum','100-200 mg/dia','Dor e inflamação','{M79.1}'::text[],true,'EMS'),
('Trometamol Cetorolaco EMS','Cetorolaco de Trometamol','EMS','Comprimido sublingual 10 mg','10mg','Comprimido sublingual','Sublingual','AINE','vermelha','branca_comum','10 mg SL até 4x/dia; máx. 5 dias','Dor moderada a intensa (genérico do Toragesic)','{R52}'::text[],true,'EMS'),
('Cloridrato de Ciclobenzaprina EMS','Ciclobenzaprina','EMS','Comprimido revestido 5 e 10 mg','5-10mg','Comprimido','Oral','Relaxante muscular','vermelha','branca_comum','5-10 mg 2-3x/dia (máx. 60 mg/dia)','Espasmo muscular, lombalgia','{M62.4,M54.5}'::text[],true,'EMS'),
('Cloridrato de Tramadol EMS','Tramadol','EMS','Cápsula 50 mg; comprimido LP 100 mg; gotas 100 mg/mL','50-100mg','Cápsula','Oral','Analgésico opioide','vermelha_retencao','controle_especial','50-100 mg até 4x/dia; máx. 400 mg/dia','Dor moderada a intensa','{R52.1}'::text[],true,'EMS'),
('Tramadol + Paracetamol EMS','Tramadol + Paracetamol','EMS','Comprimido 37,5+325 mg','37,5+325mg','Comprimido','Oral','Analgésico opioide + analgésico','vermelha_retencao','controle_especial','1-2 comp até 4x/dia','Dor moderada','{R52}'::text[],true,'EMS'),
('Etoricoxibe EMS','Etoricoxibe','EMS','Comprimido revestido 60 e 90 mg','60-90mg','Comprimido','Oral','AINE COX-2','vermelha','branca_comum','60-90 mg 1x/dia','Dor inflamatória, artrite','{M19,M25.5}'::text[],true,'EMS'),
('Isotretinoína EMS','Isotretinoína','EMS','Cápsula 10 e 20 mg, caixa 30','10-20mg','Cápsula','Oral','Retinoide sistêmico (C2)','vermelha','controle_especial','0,5-1 mg/kg/dia com alimentos','Acne grave (retenção de receita — lista C2)','{L70.0}'::text[],true,'EMS'),
('Fluconazol EMS','Fluconazol','EMS','Cápsula 150 mg (tb. 50 e 100 mg)','150mg','Cápsula','Oral','Antifúngico','vermelha','branca_comum','150 mg dose única (candidíase vaginal)','Candidíase, micoses','{B37}'::text[],true,'EMS'),
('Itraconazol EMS','Itraconazol','EMS','Cápsula 100 mg','100mg','Cápsula','Oral','Antifúngico','vermelha','branca_comum','100-400 mg/dia com alimentos','Onicomicose, micoses sistêmicas','{B35}'::text[],true,'EMS'),
('Aciclovir EMS','Aciclovir','EMS','Comprimido 200 e 400 mg; creme 50 mg/g','200-400mg','Comprimido','Oral','Antiviral','vermelha','branca_comum','400 mg 3x/dia ou 200 mg 5x/dia por 5-10 dias','Herpes simples e zóster','{B00,B02}'::text[],true,'EMS'),
('Finasterida EMS','Finasterida','EMS','Comprimido revestido 1 mg (alopecia) e 5 mg (HPB)','1-5mg','Comprimido','Oral','Inibidor 5-alfa-redutase','vermelha','branca_comum','1 mg/dia (alopecia); 5 mg/dia (HPB)','Alopecia androgenética, HPB','{L64,N40}'::text[],true,'EMS'),
('Minoxidil EMS','Minoxidil','EMS','Solução capilar 5% (50 mg/mL), frasco 50 mL','50mg/mL','Solução tópica','Tópica','Estimulante capilar','livre','branca_comum','1 mL 2x/dia no couro cabeludo seco','Alopecia androgenética','{L64}'::text[],true,'EMS'),
('Ivermectina EMS','Ivermectina','EMS','Comprimido 6 mg','6mg','Comprimido','Oral','Antiparasitário','vermelha','branca_comum','200 mcg/kg dose única','Escabiose, pediculose, estrongiloidíase','{B86,B85}'::text[],true,'EMS'),
('Valerato de Betametasona EMS','Betametasona','EMS','Creme/pomada 1 mg/g','1mg/g','Creme','Tópica','Corticosteroide tópico','vermelha','branca_comum','Camada fina 1-2x/dia por período curto','Dermatoses inflamatórias','{L20,L30}'::text[],true,'EMS')
) AS v(nome_comercial, principio_ativo, laboratorio, apresentacao, concentracao, forma_farmaceutica, via_administracao, classe_terapeutica, tarja, tipo_receita, posologia_referencia, indicacoes, cid10_relacionados, is_parceiro, parceiro_nome)
WHERE NOT EXISTS (SELECT 1 FROM public.medications m WHERE lower(m.nome_comercial) = lower(v.nome_comercial));

-- PARTE 3 — NOVOS MEDICAMENTOS EUROFARMA
INSERT INTO public.medications (nome_comercial, principio_ativo, laboratorio, apresentacao, concentracao, forma_farmaceutica, via_administracao, classe_terapeutica, tarja, tipo_receita, posologia_referencia, indicacoes, cid10_relacionados, is_parceiro, parceiro_nome)
SELECT v.* FROM (VALUES
('Zart','Losartana Potássica','Eurofarma','Comprimido 50 mg, caixa 30','50mg','Comprimido','Oral','Anti-hipertensivo - BRA','vermelha','branca_comum','50-100 mg 1x/dia','Hipertensão arterial','{I10}'::text[],true,'Eurofarma'),
('Zart H','Losartana + Hidroclorotiazida','Eurofarma','Comprimido 50+12,5 e 100+25 mg','50+12,5mg','Comprimido','Oral','BRA + diurético tiazídico','vermelha','branca_comum','1 comp 1x/dia','Hipertensão arterial','{I10}'::text[],true,'Eurofarma'),
('Anaten','Anlodipino + Atenolol','Eurofarma','Comprimido 5+25 e 5+50 mg, caixa 30','5+50mg','Comprimido','Oral','BCC + beta-bloqueador','vermelha','branca_comum','1 comp 1x/dia','Hipertensão, angina','{I10,I20}'::text[],true,'Eurofarma'),
('Vast','Atorvastatina Cálcica','Eurofarma','Comprimido 10, 20 e 40 mg','10-40mg','Comprimido','Oral','Hipolipemiante - Estatina','vermelha','branca_comum','10-80 mg 1x/dia','Dislipidemia','{E78.5}'::text[],true,'Eurofarma'),
('RUVA','Rosuvastatina Cálcica','Eurofarma','Comprimido revestido 5, 10 e 20 mg, caixa 30','5-20mg','Comprimido','Oral','Hipolipemiante - Estatina','vermelha','branca_comum','10 mg 1x/dia (5-40 mg)','Dislipidemia','{E78.0}'::text[],true,'Eurofarma'),
('Rosuvastatina Cálcica Eurofarma','Rosuvastatina Cálcica','Eurofarma','Comprimido revestido 5, 10 e 20 mg','5-20mg','Comprimido','Oral','Hipolipemiante - Estatina','vermelha','branca_comum','10 mg 1x/dia','Dislipidemia','{E78.0}'::text[],true,'Eurofarma'),
('Plaq','Clopidogrel','Eurofarma','Comprimido revestido 75 mg, caixa 10/30','75mg','Comprimido','Oral','Antiagregante plaquetário','vermelha','branca_comum','75 mg 1x/dia','SCA, AVC, doença coronariana','{I25.9,I21,I63}'::text[],true,'Eurofarma'),
('Espironolactona Eurofarma','Espironolactona','Eurofarma','Comprimido 25 e 50 mg, caixa 30','25-50mg','Comprimido','Oral','Diurético poupador de K+','vermelha','branca_comum','25-100 mg/dia','ICC, HAS resistente','{I50,I10}'::text[],true,'Eurofarma'),
('Glif','Dapagliflozina','Eurofarma','Comprimido revestido 10 mg, caixa 30','10mg','Comprimido','Oral','Antidiabético - iSGLT2','vermelha','branca_comum','10 mg 1x/dia','DM2, ICC, DRC','{E11,I50,N18}'::text[],true,'Eurofarma'),
('Dapagliflozina + Metformina XR Eurofarma','Dapagliflozina + Metformina','Eurofarma','Comprimido liberação prolongada (1º genérico do Xigduo XR)','10+1000mg','Comprimido LP','Oral','iSGLT2 + Biguanida','vermelha','branca_comum','1 comp 1x/dia com refeição','Diabetes tipo 2','{E11}'::text[],true,'Eurofarma'),
('Betes','Glimepirida','Eurofarma','Comprimido 1, 2 e 4 mg','1-4mg','Comprimido','Oral','Antidiabético - Sulfonilureia','vermelha','branca_comum','1-4 mg 1x/dia (máx. 8 mg)','Diabetes tipo 2','{E11}'::text[],true,'Eurofarma'),
('Poviztra','Semaglutida','Eurofarma','Caneta SC semanal 0,25/0,5 mg (1,5 mL) e 1/1,7/2,4 mg (3 mL)','0,25-2,4mg','Solução injetável (caneta)','Subcutânea','Análogo de GLP-1 — Obesidade','vermelha','branca_comum','Início 0,25 mg/sem, escalonar até 2,4 mg/sem','Obesidade e sobrepeso com comorbidades. Parceria Novo Nordisk (2026)','{E66}'::text[],true,'Eurofarma'),
('Extensior','Semaglutida','Eurofarma','Caneta SC semanal 1,5 e 3,0 mL','0,25-1mg','Solução injetável (caneta)','Subcutânea','Análogo de GLP-1 — Antidiabético','vermelha','branca_comum','Início 0,25 mg/sem; manutenção 0,5-1 mg/sem','Diabetes tipo 2. Parceria Novo Nordisk (2026)','{E11}'::text[],true,'Eurofarma'),
('Assert','Sertralina','Eurofarma','Comprimido revestido 50 e 100 mg','50-100mg','Comprimido','Oral','Antidepressivo - ISRS','vermelha','controle_especial','50 mg 1x/dia; máx. 200 mg/dia','Depressão, TOC, pânico','{F32,F42,F41}'::text[],true,'Eurofarma'),
('Sertralina Eurofarma','Sertralina','Eurofarma','Comprimido 25, 50 e 100 mg, caixa 30','25-100mg','Comprimido','Oral','Antidepressivo - ISRS','vermelha','controle_especial','50 mg 1x/dia; máx. 200 mg/dia','Depressão e ansiedade','{F32.9,F41.9}'::text[],true,'Eurofarma'),
('Esc','Escitalopram','Eurofarma','Comprimido/ODT 5, 10, 15 e 20 mg; solução oral 20 mg/mL','5-20mg','Comprimido','Oral','Antidepressivo - ISRS','vermelha','controle_especial','10 mg 1x/dia; máx. 20 mg/dia','Depressão e ansiedade','{F32,F41}'::text[],true,'Eurofarma'),
('Escitalopram Eurofarma','Escitalopram','Eurofarma','Comprimido 10 e 20 mg, caixa 30','10-20mg','Comprimido','Oral','Antidepressivo - ISRS','vermelha','controle_especial','10 mg 1x/dia','Depressão e ansiedade','{F32.9}'::text[],true,'Eurofarma'),
('Fluoxetina Eurofarma','Fluoxetina','Eurofarma','Cápsula 20 mg, caixa 28/30/60','20mg','Cápsula','Oral','Antidepressivo - ISRS','vermelha','controle_especial','20 mg pela manhã; máx. 80 mg/dia','Depressão e TOC','{F32.9,F42}'::text[],true,'Eurofarma'),
('Pondera','Paroxetina','Eurofarma','Comprimido 20 e 40 mg; XR liberação prolongada','20-40mg','Comprimido','Oral','Antidepressivo - ISRS','vermelha','controle_especial','20 mg 1x/dia pela manhã; máx. 50 mg/dia','Depressão, ansiedade, pânico','{F32,F41}'::text[],true,'Eurofarma'),
('Venlaxin XR','Venlafaxina','Eurofarma','Cápsula liberação prolongada 37,5, 75 e 150 mg','37,5-150mg','Cápsula LP','Oral','Antidepressivo - IRSN','vermelha','controle_especial','75 mg 1x/dia; máx. 225 mg/dia','Depressão, TAG','{F32,F41.1}'::text[],true,'Eurofarma'),
('Desve','Desvenlafaxina','Eurofarma','Comprimido liberação prolongada 50 e 100 mg','50-100mg','Comprimido LP','Oral','Antidepressivo - IRSN','vermelha','controle_especial','50 mg 1x/dia; máx. 200 mg/dia','Depressão','{F32}'::text[],true,'Eurofarma'),
('Bup XL','Bupropiona','Eurofarma','Comprimido 150 mg (12h) e XL 150/300 mg (24h)','150-300mg','Comprimido LP','Oral','Antidepressivo atípico','vermelha','controle_especial','150-300 mg/dia (XL 1x/dia pela manhã)','Depressão, cessação do tabagismo','{F32,F17}'::text[],true,'Eurofarma'),
('Sonic','Trazodona','Eurofarma','Comprimido 50 mg (cx 60) e 100 mg (cx 30)','50-100mg','Comprimido','Oral','Antidepressivo atípico','vermelha','controle_especial','50-100 mg à noite; até 300 mg/dia','Depressão, insônia','{F32,G47}'::text[],true,'Eurofarma'),
('Quet','Quetiapina','Eurofarma','Comprimido 25, 100 e 200 mg; Quet XR liberação prolongada','25-200mg','Comprimido','Oral','Antipsicótico atípico','vermelha','controle_especial','Titulação; usual 300-800 mg/dia','Esquizofrenia, bipolar','{F20,F31}'::text[],true,'Eurofarma'),
('Riss','Risperidona','Eurofarma','Comprimido 1, 2 e 3 mg','1-3mg','Comprimido','Oral','Antipsicótico atípico','vermelha','controle_especial','1-6 mg/dia','Esquizofrenia, agitação','{F20}'::text[],true,'Eurofarma'),
('Clonazepam Eurofarma','Clonazepam','Eurofarma','Comprimido 2 mg, caixa 30','2mg','Comprimido','Oral','Benzodiazepínico (B1)','preta','azul_b','0,5-2 mg/dia (ansiedade)','Ansiedade, convulsões','{F41.9,G40.9}'::text[],true,'Eurofarma'),
('Alprazolam Eurofarma','Alprazolam','Eurofarma','Comprimido 1 e 2 mg','1-2mg','Comprimido','Oral','Benzodiazepínico (B1)','preta','azul_b','0,5-4 mg/dia divididos','Transtornos de ansiedade','{F41.1}'::text[],true,'Eurofarma'),
('Turno','Zolpidem','Eurofarma','Comprimido 10 mg; SL 5 mg; Turno XR 6,25 e 12,5 mg','5-12,5mg','Comprimido','Oral','Hipnótico não-benzodiazepínico (B1)','preta','azul_b','10 mg ao deitar (5 mg SL em idosos)','Insônia','{G47.0}'::text[],true,'Eurofarma'),
('Gabapentina Eurofarma','Gabapentina','Eurofarma','Cápsula 300 e 400 mg, caixa 30','300-400mg','Cápsula','Oral','Anticonvulsivante','vermelha','controle_especial','900-1.800 mg/dia em 3 tomadas','Dor neuropática, epilepsia','{G62,G40}'::text[],true,'Eurofarma'),
('Limiar','Pregabalina','Eurofarma','Cápsula 75 e 150 mg, caixa 7/30','75-150mg','Cápsula','Oral','Anticonvulsivante/Dor neuropática','vermelha','controle_especial','150-600 mg/dia em 2 tomadas','Dor neuropática, fibromialgia','{G62,M79.7}'::text[],true,'Eurofarma'),
('Lamotrigina Eurofarma','Lamotrigina','Eurofarma','Comprimido 25, 50 e 100 mg, caixa 30','25-100mg','Comprimido','Oral','Antiepiléptico/Estabilizador de humor','vermelha','controle_especial','Titulação de 25 mg/dia até 100-200 mg/dia','Epilepsia, transtorno bipolar','{G40,F31}'::text[],true,'Eurofarma'),
('GABA ER','Divalproato de Sódio','Eurofarma','Comprimido liberação prolongada 250 e 500 mg','250-500mg','Comprimido LP','Oral','Antiepiléptico/Estabilizador de humor','vermelha','controle_especial','1x/dia (ER); 10-15 mg/kg/dia','Epilepsia, bipolar','{G40,F31}'::text[],true,'Eurofarma'),
('Amato','Topiramato','Eurofarma','Comprimido 50 mg','50mg','Comprimido','Oral','Antiepiléptico','vermelha','controle_especial','200-400 mg/dia em 2 tomadas (enxaqueca: 100 mg/dia)','Epilepsia, profilaxia de enxaqueca','{G40,G43}'::text[],true,'Eurofarma'),
('Antara','Levetiracetam','Eurofarma','Comprimido 250 e 750 mg; XR 500/750 mg; solução 100 mg/mL; IV','250-750mg','Comprimido','Oral','Antiepiléptico','vermelha','controle_especial','500 mg 2x/dia; até 1.500 mg 2x/dia','Epilepsia','{G40}'::text[],true,'Eurofarma'),
('Amitriptilina Eurofarma','Amitriptilina','Eurofarma','Comprimido revestido 25 mg, caixa 20','25mg','Comprimido','Oral','Antidepressivo tricíclico','vermelha','controle_especial','25-75 mg à noite','Depressão, dor crônica, enxaqueca','{F32,G43}'::text[],true,'Eurofarma'),
('Don','Donepezila','Eurofarma','Comprimido 5 e 10 mg, caixa 10/30','5-10mg','Comprimido','Oral','Anticolinesterásico','vermelha','controle_especial','5 mg/dia à noite; 10 mg após 4-6 semanas','Doença de Alzheimer','{G30,F03}'::text[],true,'Eurofarma'),
('Sinot','Amoxicilina','Eurofarma','Comprimido 875 mg cx 20; suspensão 250 e 500 mg/5 mL','875mg','Comprimido','Oral','Antibiótico - Penicilina','vermelha','antimicrobiano','500 mg 8/8h ou 875 mg 12/12h','Infecções bacterianas de vias aéreas','{J02.9,J03.9,J20.9}'::text[],true,'Eurofarma'),
('Amoxicilina Eurofarma','Amoxicilina','Eurofarma','Comprimido 875 mg; suspensão 250 e 500 mg/5 mL','875mg','Comprimido','Oral','Antibiótico - Penicilina','vermelha','antimicrobiano','500 mg 8/8h ou 875 mg 12/12h','Infecções bacterianas','{J02.9,J03.9,N39.0}'::text[],true,'Eurofarma'),
('Sinot Clav','Amoxicilina + Clavulanato','Eurofarma','Comprimido 875+125 mg cx 14; suspensão 400+57 mg/5 mL','875+125mg','Comprimido','Oral','Antibiótico - Penicilina + inibidor','vermelha','antimicrobiano','875+125 mg 12/12h às refeições','Sinusite, OMA, infecção respiratória','{J32,H66,J20}'::text[],true,'Eurofarma'),
('Astro','Azitromicina','Eurofarma','Comprimido 500 mg cx 3/5; suspensão; Astro IV hospitalar','500mg','Comprimido','Oral','Antibiótico - Macrolídeo','vermelha','antimicrobiano','500 mg 1x/dia por 3-5 dias','Infecções respiratórias, ISTs','{J20.9,J18.9,A56.0}'::text[],true,'Eurofarma'),
('Azitromicina Eurofarma','Azitromicina','Eurofarma','Comprimido 500 mg, caixa 3/5','500mg','Comprimido','Oral','Antibiótico - Macrolídeo','vermelha','antimicrobiano','500 mg 1x/dia por 3-5 dias','Infecções respiratórias','{J20.9}'::text[],true,'Eurofarma'),
('Cefalexina Eurofarma','Cefalexina','Eurofarma','Comprimido 500 mg; suspensão 250 mg/5 mL','500mg','Comprimido','Oral','Antibiótico - Cefalosporina 1ª geração','vermelha','antimicrobiano','500 mg 6/6h por 7-10 dias','Infecção de pele, ITU','{L03,N39.0}'::text[],true,'Eurofarma'),
('Axetilcefuroxima Eurofarma','Cefuroxima (axetil)','Eurofarma','Comprimido 250 e 500 mg, caixa 10/14','250-500mg','Comprimido','Oral','Antibiótico - Cefalosporina 2ª geração','vermelha','antimicrobiano','250-500 mg 12/12h após alimentos','ITU, sinusite, pneumonia','{J32,N39.0}'::text[],true,'Eurofarma'),
('Ciprofloxacino Eurofarma','Ciprofloxacino','Eurofarma','Comprimido 500 mg, caixa 14','500mg','Comprimido','Oral','Antibiótico - Quinolona','vermelha','antimicrobiano','250-750 mg 12/12h','ITU, infecções gastrointestinais','{N39.0,A09.9}'::text[],true,'Eurofarma'),
('Levofloxacino Eurofarma','Levofloxacino','Eurofarma','Comprimido 500 mg cx 7/10; 750 mg','500-750mg','Comprimido','Oral','Antibiótico - Quinolona','vermelha','antimicrobiano','500 mg 1x/dia (pneumonia: 750 mg) por 7-14 dias','Pneumonia, ITU complicada','{J18,N39.0}'::text[],true,'Eurofarma'),
('Subtrax','Sulfametoxazol + Trimetoprima','Eurofarma','Comprimido 800+160 mg cx 10; suspensão 400+80 mg/5 mL','800+160mg','Comprimido','Oral','Antibiótico - Sulfa','vermelha','antimicrobiano','800+160 mg 12/12h por 7-10 dias','ITU, infecções respiratórias','{N39.0}'::text[],true,'Eurofarma'),
('Ceftriaxona Sódica Eurofarma','Ceftriaxona','Eurofarma','Pó injetável 500 mg e 1 g (hospitalar)','500mg-1g','Injetável','IV/IM','Antibiótico - Cefalosporina 3ª geração','vermelha','antimicrobiano','1-2 g IV/IM 1x/dia','Pneumonia, meningite, pielonefrite','{J18,G00,N10}'::text[],true,'Eurofarma'),
('Omeprazol Eurofarma','Omeprazol','Eurofarma','Cápsula 20 mg, caixa 7/28; IV hospitalar','20mg','Cápsula','Oral','Inibidor de bomba de prótons','vermelha','branca_comum','20 mg 1x/dia em jejum por 4-8 semanas','DRGE, gastrite, úlcera','{K21.9,K29.7,K25.9}'::text[],true,'Eurofarma'),
('Pantocal','Pantoprazol','Eurofarma','Comprimido liberação retardada 20 e 40 mg, caixa 28','20-40mg','Comprimido','Oral','Inibidor de bomba de prótons','vermelha','branca_comum','40 mg 1x/dia antes do café','DRGE, úlcera péptica','{K21.9,K25.9}'::text[],true,'Eurofarma'),
('Ésio','Esomeprazol','Eurofarma','Comprimido 20 e 40 mg, caixa 7/28','20-40mg','Comprimido','Oral','Inibidor de bomba de prótons','vermelha','branca_comum','20-40 mg 1x/dia','DRGE','{K21}'::text[],true,'Eurofarma'),
('Domperix','Domperidona','Eurofarma','Comprimido 10 mg cx 30/60; suspensão 1 mg/mL','10mg','Comprimido','Oral','Procinético','vermelha','branca_comum','10 mg 3x/dia antes das refeições','Náusea, vômito, dispepsia','{R11,K30}'::text[],true,'Eurofarma'),
('Domperidona Eurofarma','Domperidona','Eurofarma','Comprimido 10 mg; suspensão 1 mg/mL','10mg','Comprimido','Oral','Procinético','vermelha','branca_comum','10 mg 3x/dia antes das refeições','Náusea, vômito, dispepsia','{R11}'::text[],true,'Eurofarma'),
('Digesan','Bromoprida','Eurofarma','Cápsula 10 mg cx 20; gotas 4 mg/mL','10mg','Cápsula','Oral','Antiemético/Procinético','vermelha','branca_comum','10 mg 2-3x/dia antes das refeições','Náuseas, vômitos, dispepsia','{R11,K30}'::text[],true,'Eurofarma'),
('Simeticona Eurofarma','Simeticona','Eurofarma','Cápsula 125 mg, caixa 10','125mg','Cápsula','Oral','Antiflatulento','livre','branca_comum','125 mg 3-4x/dia após refeições','Gases, distensão abdominal','{R14}'::text[],true,'Eurofarma'),
('Noex','Budesonida','Eurofarma','Spray nasal 32 e 64 mcg/dose (120 doses); 50 e 100 mcg','32-64mcg','Spray nasal','Nasal','Corticosteroide nasal','vermelha','branca_comum','64-256 mcg/dia; titular à menor dose eficaz','Rinite alérgica','{J30}'::text[],true,'Eurofarma'),
('Montelucaste de Sódio Eurofarma','Montelucaste','Eurofarma','Comprimido mastigável 4 e 5 mg; revestido 10 mg','4-10mg','Comprimido','Oral','Antileucotrieno','vermelha','branca_comum','10 mg 1x/dia à noite','Asma, rinite alérgica','{J45,J30}'::text[],true,'Eurofarma'),
('Desloratadina Eurofarma','Desloratadina','Eurofarma','Comprimido 5 mg cx 10/30; xarope 0,5 mg/mL','5mg','Comprimido','Oral','Anti-histamínico','livre','branca_comum','5 mg 1x/dia','Rinite alérgica, urticária','{J30,L50}'::text[],true,'Eurofarma'),
('Fexofenadina Eurofarma','Fexofenadina','Eurofarma','Comprimido 120 e 180 mg cx 10; suspensão 6 mg/mL','120-180mg','Comprimido','Oral','Anti-histamínico não sedativo','livre','branca_comum','120-180 mg 1x/dia','Rinite alérgica, urticária','{J30.4,L50.9}'::text[],true,'Eurofarma'),
('Levocetirizina Eurofarma','Levocetirizina','Eurofarma','Comprimido 5 mg','5mg','Comprimido','Oral','Anti-histamínico','livre','branca_comum','5 mg 1x/dia','Alergia','{J30,L50}'::text[],true,'Eurofarma'),
('Hidroxizina Eurofarma','Hidroxizina','Eurofarma','Solução oral 2 mg/mL, frasco 120 mL','2mg/mL','Solução oral','Oral','Anti-histamínico','vermelha','branca_comum','25 mg 3-4x/dia','Prurido, urticária','{L29.9,L50.9}'::text[],true,'Eurofarma'),
('Preni','Prednisolona','Eurofarma','Comprimido 5, 20 e 40 mg; solução oral','5-40mg','Comprimido','Oral','Corticosteroide','vermelha','branca_comum','5-60 mg/dia (pediátrico ~1 mg/kg/dia)','Processos alérgicos e inflamatórios','{J45.9,L20.9}'::text[],true,'Eurofarma'),
('Prednisolona Eurofarma','Prednisolona','Eurofarma','Comprimido 5 e 20 mg; solução 3 mg/mL; gotas 11 mg/mL','3mg/mL','Solução oral','Oral','Corticosteroide','vermelha','branca_comum','Conforme prescrição (1 mg/kg/dia pediátrico)','Processos alérgicos e inflamatórios','{J45.9,L20.9}'::text[],true,'Eurofarma'),
('Prednisona Eurofarma','Prednisona','Eurofarma','Comprimido 20 mg (embalagem fracionável 60)','20mg','Comprimido','Oral','Corticosteroide','vermelha','branca_comum','5-60 mg/dia, dose única matinal','Doenças inflamatórias e autoimunes','{J45.9,M06.9}'::text[],true,'Eurofarma'),
('Acetilcisteína Eurofarma','Acetilcisteína','Eurofarma','Xarope 20 mg/mL (infantil) e 40 mg/mL (adulto)','20-40mg/mL','Xarope','Oral','Mucolítico','livre','branca_comum','600 mg 1x/dia por 5-10 dias','Tosse produtiva','{R05}'::text[],true,'Eurofarma'),
('Drospirenona + Etinilestradiol Eurofarma','Drospirenona + Etinilestradiol','Eurofarma','Comprimido 3+0,03 mg (21/28/63) e 3+0,02 mg (24)','3+0,03mg','Comprimido','Oral','Contraceptivo combinado','vermelha','branca_comum','1 comp/dia; 21+7 ou 24+4','Contracepção hormonal','{Z30}'::text[],true,'Eurofarma'),
('Tâmisa 30','Etinilestradiol + Gestodeno','Eurofarma','Drágea 0,030+0,075 mg, cartela 21/28/63','30mcg+75mcg','Drágea','Oral','Contraceptivo oral combinado','vermelha','branca_comum','1 drágea ao dia por 21 dias + 7 pausa','Contracepção hormonal (divisão Momenta)','{Z30.0}'::text[],true,'Eurofarma'),
('Desogestrel Eurofarma','Desogestrel','Eurofarma','Comprimido 75 mcg, 28 ou 84 comp.','75mcg','Comprimido','Oral','Contraceptivo progestágeno','vermelha','branca_comum','1 comp/dia contínuo, sem pausa','Contracepção (incl. amamentação)','{Z30}'::text[],true,'Eurofarma'),
('Dopo','Levonorgestrel','Eurofarma','Comprimido 0,75 mg, 2 comprimidos','0,75mg','Comprimido','Oral','Contracepção de emergência','vermelha','branca_comum','1 comp até 72h após o coito + 1 comp 12h depois','Contracepção de emergência','{Z30}'::text[],true,'Eurofarma'),
('Drospirenona + Estradiol Eurofarma','Drospirenona + Estradiol','Eurofarma','Comprimido 2+1 mg, caixa 28 (1º genérico TRH)','2+1mg','Comprimido','Oral','TRH combinada','vermelha','branca_comum','1 comp/dia contínuo','Terapia de reposição hormonal','{N95}'::text[],true,'Eurofarma'),
('Dipirona Sódica Eurofarma','Dipirona Sódica','Eurofarma','Gotas 500 mg/mL, frasco 10/20 mL','500mg/mL','Gotas','Oral','Analgésico/Antipirético','livre','branca_comum','20-40 gotas até 4x/dia','Dor e febre','{R52.9,R50.9}'::text[],true,'Eurofarma'),
('Paco','Paracetamol + Codeína','Eurofarma','Comprimido 500+30 mg','500+30mg','Comprimido','Oral','Analgésico opioide','vermelha_retencao','controle_especial','1-2 comp a cada 4-6h','Dor moderada a intensa','{R52.1}'::text[],true,'Eurofarma'),
('Dualgi','Ibuprofeno + Paracetamol','Eurofarma','Comprimido revestido','-','Comprimido','Oral','AINE + analgésico','livre','branca_comum','Conforme bula, uso de curto prazo','Dor aguda','{R52}'::text[],true,'Eurofarma'),
('Nimesulida Eurofarma','Nimesulida','Eurofarma','Comprimido 100 mg, caixa 12','100mg','Comprimido','Oral','AINE','vermelha','branca_comum','100 mg 12/12h após refeições','Dor e inflamação','{M79.1}'::text[],true,'Eurofarma'),
('Naproxeno Sódico Eurofarma','Naproxeno','Eurofarma','Comprimido 550 mg, caixa 10','550mg','Comprimido','Oral','AINE','vermelha','branca_comum','550 mg 1-2x/dia','Dor e processos inflamatórios','{M79.1}'::text[],true,'Eurofarma'),
('Cetoprofeno Eurofarma','Cetoprofeno','Eurofarma','Comprimido LP 150 mg cx 10; gotas 20 mg/mL; IV','150mg','Comprimido LP','Oral','AINE','vermelha','branca_comum','150 mg LP 1x/dia','Dor e inflamação','{M79.1}'::text[],true,'Eurofarma'),
('Ciclobenzaprina Eurofarma','Ciclobenzaprina','Eurofarma','Comprimido 5 e 10 mg, caixa 15/30','5-10mg','Comprimido','Oral','Relaxante muscular','vermelha','branca_comum','20-40 mg/dia; máx. 60 mg','Espasmo muscular','{M62.4}'::text[],true,'Eurofarma'),
('Gésico','Tramadol','Eurofarma','Cápsula 50 mg; solução 100 mg/mL; Retard LP 100 mg','50-100mg','Cápsula','Oral','Analgésico opioide','vermelha_retencao','controle_especial','50-100 mg a cada 4-6h; máx. 400 mg/dia','Dor moderada a intensa','{R52.1}'::text[],true,'Eurofarma'),
('Gésico Duo','Tramadol + Paracetamol','Eurofarma','Comprimido 37,5+325 mg','37,5+325mg','Comprimido','Oral','Analgésico opioide + analgésico','vermelha_retencao','controle_especial','1-2 comp até 4x/dia','Dor moderada','{R52}'::text[],true,'Eurofarma'),
('Cafeína + Carisoprodol + Diclofenaco + Paracetamol Eurofarma','Cafeína + Carisoprodol + Diclofenaco + Paracetamol','Eurofarma','Comprimido 30+125+50+300 mg, caixa 15/30 (genérico do Tandrilax)','30+125+50+300mg','Comprimido','Oral','Relaxante muscular + AINE','vermelha','branca_comum','1 comp 12/12h; máx. 10 dias','Lombalgia, contratura muscular','{M54.5}'::text[],true,'Eurofarma'),
('Isotretinoína Eurofarma','Isotretinoína','Eurofarma','Cápsula mole 20 mg, caixa 30','20mg','Cápsula','Oral','Retinoide sistêmico (C2)','vermelha','controle_especial','0,5-1 mg/kg/dia às refeições','Acne grave (retenção de receita — lista C2)','{L70.0}'::text[],true,'Eurofarma'),
('Itraconazol Eurofarma','Itraconazol','Eurofarma','Cápsula 100 mg, caixa 4/15','100mg','Cápsula','Oral','Antifúngico','vermelha','branca_comum','100-200 mg/dia após refeição','Onicomicose, micoses','{B35}'::text[],true,'Eurofarma'),
('Aciclovir Eurofarma','Aciclovir','Eurofarma','Comprimido 200 mg cx 25; creme 50 mg/g 10 g','200mg','Comprimido','Oral','Antiviral','vermelha','branca_comum','200 mg 5x/dia por 5-10 dias','Herpes simples','{B00}'::text[],true,'Eurofarma'),
('Finasterida Eurofarma','Finasterida','Eurofarma','Comprimido 1 e 5 mg, caixa 30','1-5mg','Comprimido','Oral','Inibidor 5-alfa-redutase','vermelha','branca_comum','1 mg/dia (alopecia); 5 mg/dia (HPB)','Alopecia androgenética, HPB','{L64,N40}'::text[],true,'Eurofarma'),
('Dixil','Minoxidil','Eurofarma','Solução spray capilar 5%, frasco 25/50 mL','50mg/mL','Solução tópica','Tópica','Estimulante capilar','livre','branca_comum','1 mL 2x/dia; máx. 2 mL/dia','Alopecia androgenética (divisão Momenta)','{L64}'::text[],true,'Eurofarma')
) AS v(nome_comercial, principio_ativo, laboratorio, apresentacao, concentracao, forma_farmaceutica, via_administracao, classe_terapeutica, tarja, tipo_receita, posologia_referencia, indicacoes, cid10_relacionados, is_parceiro, parceiro_nome)
WHERE NOT EXISTS (SELECT 1 FROM public.medications m WHERE lower(m.nome_comercial) = lower(v.nome_comercial));

-- PARTE 4 — Destaque dos lançamentos
UPDATE public.medications SET destaque_ordem = 1 WHERE nome_comercial IN ('Ozivy','Poviztra','Extensior','Olire','Lirux') AND destaque_ordem = 0;