
GRANT EXECUTE ON FUNCTION public.search_medications(text, text) TO anon, authenticated;

CREATE UNIQUE INDEX IF NOT EXISTS medications_nome_comercial_key
  ON public.medications (nome_comercial);

INSERT INTO public.medications
  (nome_comercial, principio_ativo, laboratorio, apresentacao, concentracao,
   forma_farmaceutica, via_administracao, classe_terapeutica, tarja, tipo_receita,
   posologia_referencia, indicacoes, cid10_relacionados, is_parceiro, parceiro_nome, destaque_ordem)
VALUES
('Novalgina','Dipirona Sódica','Sanofi','Comprimido 500mg','500mg','Comprimido','Oral','Analgésico/Antitérmico','livre','branca_comum','1 comp VO a cada 6h se dor ou febre','Dor leve a moderada, febre','{"R50","R52"}',false,NULL,10),
('Anador','Dipirona Sódica','Boehringer','Comprimido 500mg','500mg','Comprimido','Oral','Analgésico/Antitérmico','livre','branca_comum','1 comp VO a cada 6h','Dor, febre','{"R50","R52"}',false,NULL,10),
('Tylenol DC','Paracetamol + Cafeína','Janssen','Comprimido 500mg+65mg','500mg+65mg','Comprimido','Oral','Analgésico','livre','branca_comum','1-2 comp VO a cada 6h','Cefaleia, dor leve a moderada','{"R51","R52"}',false,NULL,9),
('Paracetamol EMS','Paracetamol','EMS','Comprimido 750mg','750mg','Comprimido','Oral','Analgésico/Antitérmico','livre','branca_comum','1 comp VO a cada 6h','Dor leve, febre','{"R50","R52"}',true,'EMS',1),
('Advil','Ibuprofeno','Pfizer','Cápsula 400mg','400mg','Cápsula','Oral','AINE','livre','branca_comum','1 cáp VO a cada 8h após refeição','Dor, inflamação, febre','{"M25.5","R52"}',false,NULL,8),
('Alivium','Ibuprofeno','Mantecorp','Suspensão 50mg/mL','50mg/mL','Suspensão Oral','Oral','AINE','livre','branca_comum','10mg/kg VO a cada 8h','Febre e dor pediátrica','{"R50"}',false,NULL,8),
('Cataflam','Diclofenaco Potássico','Novartis','Comprimido 50mg','50mg','Comprimido','Oral','AINE','vermelha','branca_comum','1 comp VO a cada 8h após refeição','Dor inflamatória aguda','{"M25.5"}',false,NULL,7),
('Voltaren Emulgel','Diclofenaco Dietilamônio','Novartis','Gel 10mg/g','10mg/g','Gel tópico','Tópico','AINE tópico','livre','branca_comum','Aplicar 3-4x/dia na área','Dor músculo-esquelética localizada','{"M79.1"}',false,NULL,6),
('Feldene','Piroxicam','Pfizer','Cápsula 20mg','20mg','Cápsula','Oral','AINE','vermelha','branca_comum','1 cáp VO 1x/dia','Artrite, dor crônica','{"M19"}',false,NULL,5),
('Celebra','Celecoxibe','Pfizer','Cápsula 200mg','200mg','Cápsula','Oral','AINE COX-2','vermelha','branca_comum','1 cáp VO 1-2x/dia','Osteoartrite, dor crônica','{"M19","M25.5"}',false,NULL,5),
('Arcoxia','Etoricoxibe','MSD','Comprimido 90mg','90mg','Comprimido','Oral','AINE COX-2','vermelha','branca_comum','1 comp VO 1x/dia','Dor inflamatória, artrite','{"M19"}',false,NULL,5),
('Tandrilax','Carisoprodol + Diclofenaco + Paracetamol + Cafeína','Aché','Comprimido','125+50+300+30mg','Comprimido','Oral','Relaxante muscular + AINE','vermelha','branca_comum','1 comp VO 3x/dia','Lombalgia, dor músculo-esquelética','{"M54.5"}',false,NULL,5),
('Torsilax','Carisoprodol + Diclofenaco + Paracetamol + Cafeína','Neo Química','Comprimido','125+50+300+30mg','Comprimido','Oral','Relaxante muscular + AINE','vermelha','branca_comum','1 comp VO 3x/dia','Dor lombar, contratura','{"M54.5"}',false,NULL,5),
('Miosan','Ciclobenzaprina','Apsen','Comprimido 5mg','5mg','Comprimido','Oral','Relaxante muscular','vermelha','branca_comum','1 comp VO 3x/dia','Espasmo muscular','{"M62.4"}',false,NULL,5),
('Toragesic','Cetorolaco','EMS','Comprimido 10mg sublingual','10mg','Sublingual','Sublingual','AINE','vermelha','branca_comum','1 comp SL a cada 6h, máx 5 dias','Dor moderada a intensa','{"R52"}',true,'EMS',2),
('Dorflex','Dipirona + Orfenadrina + Cafeína','Sanofi','Comprimido','300+35+50mg','Comprimido','Oral','Analgésico + Relaxante','livre','branca_comum','1-2 comp VO a cada 6h','Dor músculo-esquelética','{"M54","R52"}',false,NULL,9),
('Codaten','Diclofenaco + Codeína','Mantecorp','Comprimido','50mg+50mg','Comprimido','Oral','AINE + Opioide fraco','preta','controle_especial','1 comp VO a cada 8h','Dor moderada a intensa','{"R52"}',false,NULL,3),
('Tylex','Paracetamol + Codeína','Janssen','Comprimido','500mg+30mg','Comprimido','Oral','Analgésico opioide','preta','controle_especial','1 comp VO a cada 6h','Dor moderada','{"R52"}',false,NULL,3),
('Keflex','Cefalexina','Eurofarma','Cápsula 500mg','500mg','Cápsula','Oral','Cefalosporina 1ª geração','vermelha','antimicrobiano','1 cáp VO a cada 6h por 7-10 dias','Infecção de pele, ITU','{"L03","N39.0"}',true,'Eurofarma',2),
('Zinnat','Cefuroxima','GSK','Comprimido 500mg','500mg','Comprimido','Oral','Cefalosporina 2ª geração','vermelha','antimicrobiano','1 comp VO a cada 12h por 7-10 dias','ITU, sinusite, pneumonia','{"J32","N39.0"}',false,NULL,4),
('Rocefin','Ceftriaxona','Roche','Pó injetável 1g','1g','Injetável','IV/IM','Cefalosporina 3ª geração','vermelha','antimicrobiano','1-2g IV/IM 1x/dia','Pneumonia, meningite, PNA','{"J18","G00"}',false,NULL,4),
('Amoxil 875','Amoxicilina + Clavulanato','GSK','Comprimido 875mg','875+125mg','Comprimido','Oral','Penicilina + inibidor','vermelha','antimicrobiano','1 comp VO a cada 12h por 7-10 dias','Sinusite, OMA, ITU','{"J32","H66"}',false,NULL,4),
('Clavulin','Amoxicilina + Clavulanato','GSK','Comprimido 500+125mg','500+125mg','Comprimido','Oral','Penicilina + inibidor','vermelha','antimicrobiano','1 comp VO a cada 8h por 7-10 dias','Infecção respiratória','{"J20"}',false,NULL,4),
('Bactrim','Sulfametoxazol + Trimetoprima','Roche','Comprimido','400+80mg','Comprimido','Oral','Sulfa','vermelha','antimicrobiano','2 comp VO a cada 12h por 7-10 dias','ITU, ITR','{"N39.0"}',false,NULL,4),
('Doxiciclina EMS','Doxiciclina','EMS','Comprimido 100mg','100mg','Comprimido','Oral','Tetraciclina','vermelha','antimicrobiano','1 comp VO a cada 12h por 7-14 dias','Acne, DST, doença de Lyme','{"L70","A56"}',true,'EMS',2),
('Levaquin','Levofloxacino','Janssen','Comprimido 500mg','500mg','Comprimido','Oral','Quinolona','vermelha','antimicrobiano','1 comp VO 1x/dia por 7-14 dias','Pneumonia, ITU complicada','{"J18","N39.0"}',false,NULL,4),
('Tavanic','Levofloxacino','Sanofi','Comprimido 500mg','500mg','Comprimido','Oral','Quinolona','vermelha','antimicrobiano','1 comp VO 1x/dia','PAC, ITU','{"J18"}',false,NULL,4),
('Floxstat','Norfloxacino','EMS','Comprimido 400mg','400mg','Comprimido','Oral','Quinolona','vermelha','antimicrobiano','1 comp VO a cada 12h por 7-10 dias','ITU','{"N39.0"}',true,'EMS',2),
('Flagyl','Metronidazol','Sanofi','Comprimido 400mg','400mg','Comprimido','Oral','Antibiótico/Antiprotozoário','vermelha','antimicrobiano','1 comp VO a cada 8h por 7 dias','Infecção anaeróbia, giardíase','{"A07"}',false,NULL,4),
('Nistatina EMS','Nistatina','EMS','Suspensão oral 100.000 UI/mL','100.000 UI/mL','Suspensão Oral','Oral/Tópica','Antifúngico','vermelha','antimicrobiano','5mL VO 4x/dia por 7-14 dias','Candidíase oral','{"B37"}',true,'EMS',2),
('Cefepima','Cefepima','EMS','Pó injetável 1g','1g','Injetável','IV/IM','Cefalosporina 4ª geração','vermelha','antimicrobiano','1-2g IV a cada 12h','Infecção hospitalar grave','{"A41"}',true,'EMS',2),
('Losartana 100','Losartana Potássica','Eurofarma','Comprimido 100mg','100mg','Comprimido','Oral','Antagonista AT1','vermelha','branca_comum','1 comp VO 1x/dia','HAS','{"I10"}',true,'Eurofarma',2),
('Diovan','Valsartana','Novartis','Comprimido 160mg','160mg','Comprimido','Oral','Antagonista AT1','vermelha','branca_comum','1 comp VO 1x/dia','HAS, ICC','{"I10","I50"}',false,NULL,5),
('Micardis','Telmisartana','Boehringer','Comprimido 40mg','40mg','Comprimido','Oral','Antagonista AT1','vermelha','branca_comum','1 comp VO 1x/dia','HAS','{"I10"}',false,NULL,5),
('Benicar','Olmesartana','Daiichi','Comprimido 40mg','40mg','Comprimido','Oral','Antagonista AT1','vermelha','branca_comum','1 comp VO 1x/dia','HAS','{"I10"}',false,NULL,5),
('Atacand','Candesartana','AstraZeneca','Comprimido 16mg','16mg','Comprimido','Oral','Antagonista AT1','vermelha','branca_comum','1 comp VO 1x/dia','HAS','{"I10"}',false,NULL,5),
('Norvasc','Anlodipino','Pfizer','Comprimido 5mg','5mg','Comprimido','Oral','Bloqueador canais de cálcio','vermelha','branca_comum','1 comp VO 1x/dia','HAS, angina','{"I10","I20"}',false,NULL,5),
('Adalat Oros','Nifedipino','Bayer','Comprimido 30mg','30mg','Comprimido liberação prolongada','Oral','Bloqueador canais de cálcio','vermelha','branca_comum','1 comp VO 1x/dia','HAS','{"I10"}',false,NULL,5),
('Concor','Bisoprolol','Merck','Comprimido 5mg','5mg','Comprimido','Oral','Beta-bloqueador','vermelha','branca_comum','1 comp VO 1x/dia','HAS, ICC','{"I10","I50"}',false,NULL,5),
('Selozok','Metoprolol','AstraZeneca','Comprimido 50mg','50mg','Comprimido','Oral','Beta-bloqueador','vermelha','branca_comum','1 comp VO 1-2x/dia','HAS, ICC, angina','{"I10","I50","I20"}',false,NULL,5),
('Carvedilol EMS','Carvedilol','EMS','Comprimido 25mg','25mg','Comprimido','Oral','Alfa/Beta-bloqueador','vermelha','branca_comum','1 comp VO 2x/dia','ICC, HAS','{"I50","I10"}',true,'EMS',2),
('Lasix','Furosemida','Sanofi','Comprimido 40mg','40mg','Comprimido','Oral','Diurético de alça','vermelha','branca_comum','1 comp VO 1-2x/dia pela manhã','Edema, ICC','{"I50"}',false,NULL,5),
('Aldactone','Espironolactona','Pfizer','Comprimido 25mg','25mg','Comprimido','Oral','Diurético poupador K+','vermelha','branca_comum','1 comp VO 1x/dia','ICC, cirrose, HAS resistente','{"I50","K70"}',false,NULL,5),
('Crestor','Rosuvastatina','AstraZeneca','Comprimido 20mg','20mg','Comprimido','Oral','Estatina','vermelha','branca_comum','1 comp VO 1x/dia à noite','Dislipidemia','{"E78.0"}',false,NULL,5),
('Lipitor','Atorvastatina','Pfizer','Comprimido 20mg','20mg','Comprimido','Oral','Estatina','vermelha','branca_comum','1 comp VO 1x/dia à noite','Dislipidemia','{"E78.0"}',false,NULL,5),
('Vytorin','Ezetimiba + Sinvastatina','MSD','Comprimido 10+20mg','10+20mg','Comprimido','Oral','Hipolipemiante','vermelha','branca_comum','1 comp VO 1x/dia à noite','Dislipidemia','{"E78"}',false,NULL,5),
('Marevan','Varfarina Sódica','Farmoquímica','Comprimido 5mg','5mg','Comprimido','Oral','Anticoagulante oral','vermelha','branca_comum','Dose individualizada conforme INR','TVP, FA, próteses','{"I48","I82"}',false,NULL,4),
('Xarelto','Rivaroxabana','Bayer','Comprimido 20mg','20mg','Comprimido','Oral','Anticoagulante DOAC','vermelha','branca_comum','1 comp VO 1x/dia com alimento','FA, TVP','{"I48","I82"}',false,NULL,4),
('Eliquis','Apixabana','Pfizer','Comprimido 5mg','5mg','Comprimido','Oral','Anticoagulante DOAC','vermelha','branca_comum','1 comp VO a cada 12h','FA, TEP','{"I48","I26"}',false,NULL,4),
('Pradaxa','Dabigatrana','Boehringer','Cápsula 150mg','150mg','Cápsula','Oral','Anticoagulante DOAC','vermelha','branca_comum','1 cáp VO a cada 12h','FA','{"I48"}',false,NULL,4),
('Plavix','Clopidogrel','Sanofi','Comprimido 75mg','75mg','Comprimido','Oral','Antiagregante','vermelha','branca_comum','1 comp VO 1x/dia','SCA, AVC, doença coronariana','{"I21","I63"}',false,NULL,4),
('Glifage','Metformina','Merck','Comprimido 850mg','850mg','Comprimido','Oral','Biguanida','vermelha','branca_comum','1 comp VO 2-3x/dia com refeições','DM2','{"E11"}',false,NULL,6),
('Galvus Met','Vildagliptina + Metformina','Novartis','Comprimido 50+1000mg','50+1000mg','Comprimido','Oral','iDPP4 + Biguanida','vermelha','branca_comum','1 comp VO a cada 12h','DM2','{"E11"}',false,NULL,5),
('Forxiga','Dapagliflozina','AstraZeneca','Comprimido 10mg','10mg','Comprimido','Oral','iSGLT2','vermelha','branca_comum','1 comp VO 1x/dia','DM2, ICC, DRC','{"E11","I50","N18"}',false,NULL,5),
('Jardiance','Empagliflozina','Boehringer','Comprimido 10mg','10mg','Comprimido','Oral','iSGLT2','vermelha','branca_comum','1 comp VO 1x/dia','DM2, ICC','{"E11","I50"}',false,NULL,5),
('Ozempic','Semaglutida','Novo Nordisk','Caneta SC','0,25-1mg/dose','Injetável','SC','Análogo GLP-1','vermelha','branca_comum','1 aplicação SC 1x/semana','DM2, controle ponderal','{"E11","E66"}',false,NULL,4),
('Trulicity','Dulaglutida','Lilly','Caneta SC 1,5mg','1,5mg','Injetável','SC','Análogo GLP-1','vermelha','branca_comum','1 aplicação SC 1x/semana','DM2','{"E11"}',false,NULL,4),
('Lantus','Insulina Glargina','Sanofi','Caneta 100UI/mL','100UI/mL','Injetável','SC','Insulina basal','vermelha','branca_comum','Dose individualizada SC 1x/dia','DM1, DM2','{"E10","E11"}',false,NULL,4),
('NovoRapid','Insulina Asparte','Novo Nordisk','Caneta 100UI/mL','100UI/mL','Injetável','SC','Insulina rápida','vermelha','branca_comum','Dose conforme glicemia/refeição','DM','{"E10","E11"}',false,NULL,4),
('Losec','Omeprazol','AstraZeneca','Cápsula 20mg','20mg','Cápsula','Oral','IBP','vermelha','branca_comum','1 cáp VO 1x/dia em jejum','DRGE, úlcera','{"K21","K25"}',false,NULL,6),
('Nexium','Esomeprazol','AstraZeneca','Comprimido 40mg','40mg','Comprimido','Oral','IBP','vermelha','branca_comum','1 comp VO 1x/dia em jejum','DRGE','{"K21"}',false,NULL,5),
('Pariet','Rabeprazol','Janssen','Comprimido 20mg','20mg','Comprimido','Oral','IBP','vermelha','branca_comum','1 comp VO 1x/dia em jejum','DRGE','{"K21"}',false,NULL,5),
('Lansoprazol EMS','Lansoprazol','EMS','Cápsula 30mg','30mg','Cápsula','Oral','IBP','vermelha','branca_comum','1 cáp VO 1x/dia em jejum','DRGE, úlcera','{"K21","K25"}',true,'EMS',2),
('Label','Domperidona','Eurofarma','Comprimido 10mg','10mg','Comprimido','Oral','Procinético','vermelha','branca_comum','1 comp VO 3x/dia antes das refeições','Náusea, vômito, dispepsia','{"R11"}',true,'Eurofarma',2),
('Vonau','Ondansetrona','Biolab','Comprimido 4mg','4mg','Comprimido','Oral','Antiemético 5HT3','vermelha','branca_comum','1 comp VO a cada 8h','Náusea/vômito intensos','{"R11"}',false,NULL,5),
('Vonau Flash','Ondansetrona','Biolab','Comprimido orodispersível 8mg','8mg','Comprimido','Oral','Antiemético 5HT3','vermelha','branca_comum','1 comp orodispersível a cada 12h','Náusea/vômito','{"R11"}',false,NULL,5),
('Imosec','Loperamida','Janssen','Cápsula 2mg','2mg','Cápsula','Oral','Antidiarreico','livre','branca_comum','2 cáp VO inicial e 1 após cada evacuação','Diarreia aguda','{"A09"}',false,NULL,6),
('Floratil','Saccharomyces boulardii','Merck','Cápsula 200mg','200mg','Cápsula','Oral','Probiótico','livre','branca_comum','1 cáp VO 1-2x/dia','Diarreia, disbiose','{"A09"}',false,NULL,5),
('Luftal','Simeticona','Reckitt','Gotas 75mg/mL','75mg/mL','Gotas','Oral','Antiflatulento','livre','branca_comum','10-15 gotas VO 3x/dia','Distensão abdominal','{"R14"}',false,NULL,5),
('Tagamet','Cimetidina','GSK','Comprimido 200mg','200mg','Comprimido','Oral','Antagonista H2','vermelha','branca_comum','1 comp VO a cada 12h','Dispepsia, úlcera','{"K25"}',false,NULL,4),
('Antak','Ranitidina','GSK','Comprimido 150mg','150mg','Comprimido','Oral','Antagonista H2','vermelha','branca_comum','1 comp VO a cada 12h','Dispepsia','{"K21"}',false,NULL,4),
('Aerolin','Salbutamol','GSK','Spray 100mcg/dose','100mcg','Aerossol','Inalatória','Broncodilatador beta-2','vermelha','branca_comum','2 jatos a cada 4-6h se broncoespasmo','Asma, DPOC','{"J45","J44"}',false,NULL,5),
('Berotec','Fenoterol','Boehringer','Solução 5mg/mL','5mg/mL','Solução para nebulização','Inalatória','Broncodilatador beta-2','vermelha','branca_comum','10-20 gotas nebulização a cada 6h','Asma, DPOC','{"J45","J44"}',false,NULL,5),
('Atrovent','Brometo de Ipratrópio','Boehringer','Solução 0,25mg/mL','0,25mg/mL','Solução para nebulização','Inalatória','Anticolinérgico','vermelha','branca_comum','20-40 gotas a cada 6-8h','DPOC, asma','{"J44"}',false,NULL,5),
('Seretide','Salmeterol + Fluticasona','GSK','Diskus 50/250mcg','50/250mcg','Inalador de pó seco','Inalatória','LABA + CI','vermelha','branca_comum','1 inalação a cada 12h','Asma persistente, DPOC','{"J45","J44"}',false,NULL,4),
('Symbicort','Formoterol + Budesonida','AstraZeneca','Turbuhaler 6/200mcg','6/200mcg','Inalador de pó seco','Inalatória','LABA + CI','vermelha','branca_comum','1-2 inalações a cada 12h','Asma, DPOC','{"J45","J44"}',false,NULL,4),
('Singulair','Montelucaste','MSD','Comprimido 10mg','10mg','Comprimido','Oral','Antileucotrieno','vermelha','branca_comum','1 comp VO 1x/dia à noite','Asma, rinite alérgica','{"J45","J30"}',false,NULL,5),
('Mucosolvan','Ambroxol','Sanofi','Xarope 30mg/5mL','30mg/5mL','Xarope','Oral','Mucolítico','livre','branca_comum','10mL VO 3x/dia','Tosse produtiva','{"R05"}',false,NULL,6),
('Fluimucil','Acetilcisteína','Zambon','Envelope 600mg','600mg','Granulado efervescente','Oral','Mucolítico','livre','branca_comum','1 env VO 1x/dia','Tosse produtiva','{"R05"}',false,NULL,6),
('Naridrin','Cloreto de Sódio + Cloreto de Benzalcônio','Mantecorp','Solução nasal','9mg/mL','Solução nasal','Nasal','Descongestionante nasal','livre','branca_comum','1-2 jatos em cada narina 2-3x/dia','Congestão nasal','{"J30"}',false,NULL,5),
('Sorine','Cloreto de Sódio','Mantecorp','Solução nasal 0,9%','9mg/mL','Solução nasal','Nasal','Solução salina','livre','branca_comum','1-2 jatos em cada narina 3-4x/dia','Higiene nasal','{"J30"}',false,NULL,5),
('Loratadina EMS','Loratadina','EMS','Comprimido 10mg','10mg','Comprimido','Oral','Anti-histamínico','livre','branca_comum','1 comp VO 1x/dia','Rinite alérgica, urticária','{"J30","L50"}',true,'EMS',2),
('Allegra D','Fexofenadina + Pseudoefedrina','Sanofi','Comprimido','120+60mg','Comprimido','Oral','Anti-histamínico + descongestionante','vermelha','branca_comum','1 comp VO a cada 12h','Rinite alérgica com congestão','{"J30"}',false,NULL,5),
('Claritin','Loratadina','Bayer','Comprimido 10mg','10mg','Comprimido','Oral','Anti-histamínico','livre','branca_comum','1 comp VO 1x/dia','Alergia','{"J30","L50"}',false,NULL,5),
('Desalex','Desloratadina','Mantecorp','Comprimido 5mg','5mg','Comprimido','Oral','Anti-histamínico','livre','branca_comum','1 comp VO 1x/dia','Rinite, urticária','{"J30","L50"}',false,NULL,5),
('Histamin','Cetirizina','Eurofarma','Comprimido 10mg','10mg','Comprimido','Oral','Anti-histamínico','livre','branca_comum','1 comp VO 1x/dia','Alergia','{"J30","L50"}',true,'Eurofarma',2),
('Reactine','Cetirizina','Pfizer','Comprimido 10mg','10mg','Comprimido','Oral','Anti-histamínico','livre','branca_comum','1 comp VO 1x/dia','Alergia','{"J30"}',false,NULL,4),
('Lexapro','Escitalopram','Lundbeck','Comprimido 10mg','10mg','Comprimido','Oral','ISRS','vermelha','branca_comum','1 comp VO 1x/dia','Depressão, ansiedade','{"F32","F41"}',false,NULL,5),
('Zoloft','Sertralina','Pfizer','Comprimido 50mg','50mg','Comprimido','Oral','ISRS','vermelha','branca_comum','1 comp VO 1x/dia','Depressão, TOC, TAG','{"F32","F42","F41"}',false,NULL,5),
('Prozac','Fluoxetina','Lilly','Cápsula 20mg','20mg','Cápsula','Oral','ISRS','vermelha','branca_comum','1 cáp VO 1x/dia pela manhã','Depressão, bulimia','{"F32"}',false,NULL,5),
('Venlift','Venlafaxina','Wyeth','Cápsula 75mg','75mg','Cápsula liberação prolongada','Oral','IRSN','vermelha','branca_comum','1 cáp VO 1x/dia','Depressão, TAG','{"F32","F41.1"}',false,NULL,5),
('Cymbalta','Duloxetina','Lilly','Cápsula 60mg','60mg','Cápsula','Oral','IRSN','vermelha','branca_comum','1 cáp VO 1x/dia','Depressão, dor neuropática','{"F32","G62"}',false,NULL,5),
('Wellbutrin XL','Bupropiona','GSK','Comprimido 300mg','300mg','Comprimido liberação prolongada','Oral','Antidepressivo atípico','vermelha','branca_comum','1 comp VO 1x/dia pela manhã','Depressão, cessação tabagismo','{"F32","F17"}',false,NULL,5),
('Remeron','Mirtazapina','MSD','Comprimido 30mg','30mg','Comprimido','Oral','Antidepressivo atípico','vermelha','branca_comum','1 comp VO 1x/dia à noite','Depressão, insônia','{"F32","G47"}',false,NULL,5),
('Trazodone EMS','Trazodona','EMS','Comprimido 50mg','50mg','Comprimido','Oral','Antidepressivo atípico','vermelha','branca_comum','1 comp VO à noite','Depressão, insônia','{"F32","G47"}',true,'EMS',2),
('Lamictal','Lamotrigina','GSK','Comprimido 100mg','100mg','Comprimido','Oral','Antiepiléptico/Estabilizador humor','vermelha','branca_comum','Titulação até 200mg/dia','Epilepsia, transtorno bipolar','{"G40","F31"}',false,NULL,4),
('Depakote','Divalproato de Sódio','Abbott','Comprimido 500mg','500mg','Comprimido','Oral','Antiepiléptico/Estabilizador humor','vermelha','branca_comum','1 comp VO 2x/dia','Epilepsia, bipolar, enxaqueca','{"G40","F31","G43"}',false,NULL,4),
('Tegretol','Carbamazepina','Novartis','Comprimido 200mg','200mg','Comprimido','Oral','Antiepiléptico','vermelha','branca_comum','1 comp VO 2-3x/dia','Epilepsia, neuralgia trigêmeo','{"G40","G50.0"}',false,NULL,4),
('Lyrica','Pregabalina','Pfizer','Cápsula 75mg','75mg','Cápsula','Oral','Anticonvulsivante/Neuropático','vermelha','branca_comum','1 cáp VO a cada 12h','Dor neuropática, fibromialgia','{"G62","M79.7"}',false,NULL,4),
('Neurontin','Gabapentina','Pfizer','Cápsula 300mg','300mg','Cápsula','Oral','Anticonvulsivante','vermelha','branca_comum','1 cáp VO 3x/dia','Dor neuropática, epilepsia','{"G62","G40"}',false,NULL,4),
('Risperdal','Risperidona','Janssen','Comprimido 2mg','2mg','Comprimido','Oral','Antipsicótico atípico','vermelha','branca_comum','1 comp VO 1-2x/dia','Esquizofrenia, agitação','{"F20"}',false,NULL,4),
('Seroquel XRO','Quetiapina','AstraZeneca','Comprimido 200mg','200mg','Comprimido liberação prolongada','Oral','Antipsicótico atípico','vermelha','branca_comum','1 comp VO 1x/dia à noite','Esquizofrenia, bipolar','{"F20","F31"}',false,NULL,4),
('Zyprexa','Olanzapina','Lilly','Comprimido 10mg','10mg','Comprimido','Oral','Antipsicótico atípico','vermelha','branca_comum','1 comp VO 1x/dia','Esquizofrenia, bipolar','{"F20","F31"}',false,NULL,4),
('Abilify','Aripiprazol','Otsuka','Comprimido 15mg','15mg','Comprimido','Oral','Antipsicótico atípico','vermelha','branca_comum','1 comp VO 1x/dia','Esquizofrenia, bipolar','{"F20","F31"}',false,NULL,4),
('Haldol','Haloperidol','Janssen','Comprimido 5mg','5mg','Comprimido','Oral','Antipsicótico típico','vermelha','branca_comum','1 comp VO 1-3x/dia','Psicose, agitação','{"F20"}',false,NULL,4),
('Lexotan','Bromazepam','Roche','Comprimido 3mg','3mg','Comprimido','Oral','Benzodiazepínico','preta','azul_b','1 comp VO até 3x/dia','Ansiedade','{"F41"}',false,NULL,3),
('Valium','Diazepam','Roche','Comprimido 10mg','10mg','Comprimido','Oral','Benzodiazepínico','preta','azul_b','1 comp VO 1-3x/dia','Ansiedade, espasmo muscular','{"F41","M62.4"}',false,NULL,3),
('Stilnox','Zolpidem','Sanofi','Comprimido 10mg','10mg','Comprimido','Oral','Hipnótico não-benzo','preta','azul_b','1 comp VO ao deitar','Insônia','{"G47.0"}',false,NULL,3),
('Donaren','Trazodona','Apsen','Comprimido 50mg','50mg','Comprimido','Oral','Antidepressivo/Sedativo','vermelha','branca_comum','1 comp VO à noite','Insônia, depressão','{"G47","F32"}',false,NULL,4),
('Synthroid','Levotiroxina','Abbott','Comprimido 50mcg','50mcg','Comprimido','Oral','Hormônio tireoidiano','vermelha','branca_comum','1 comp VO 1x/dia em jejum','Hipotireoidismo','{"E03"}',false,NULL,5),
('Euthyrox','Levotiroxina','Merck','Comprimido 75mcg','75mcg','Comprimido','Oral','Hormônio tireoidiano','vermelha','branca_comum','1 comp VO 1x/dia em jejum','Hipotireoidismo','{"E03"}',false,NULL,5),
('Tapazol','Metimazol','Eurofarma','Comprimido 10mg','10mg','Comprimido','Oral','Antitireoidiano','vermelha','branca_comum','1 comp VO 2-3x/dia','Hipertireoidismo','{"E05"}',true,'Eurofarma',2),
('Selene','Acetato de Ciproterona + Etinilestradiol','Eurofarma','Comprimido','2mg+0,035mg','Comprimido','Oral','Contraceptivo combinado','vermelha','branca_comum','1 comp VO/dia por 21 dias','Acne hormonal, SOP','{"L70","E28.2"}',true,'Eurofarma',2),
('Yasmin','Drospirenona + Etinilestradiol','Bayer','Comprimido','3mg+0,03mg','Comprimido','Oral','Contraceptivo combinado','vermelha','branca_comum','1 comp VO/dia por 21 dias','Contracepção','{"Z30"}',false,NULL,4),
('Cerazette','Desogestrel','MSD','Comprimido 75mcg','75mcg','Comprimido','Oral','Contraceptivo progestágeno','vermelha','branca_comum','1 comp VO/dia continuamente','Contracepção (amamentação)','{"Z30"}',false,NULL,4),
('Postinor','Levonorgestrel','Eurofarma','Comprimido 1,5mg','1,5mg','Comprimido','Oral','Contracepção de emergência','vermelha','branca_comum','1 comp VO até 72h após relação','Contracepção de emergência','{"Z30"}',true,'Eurofarma',2),
('Avodart','Dutasterida','GSK','Cápsula 0,5mg','0,5mg','Cápsula','Oral','Inibidor 5-alfa-redutase','vermelha','branca_comum','1 cáp VO 1x/dia','HPB','{"N40"}',false,NULL,4),
('Proscar','Finasterida','MSD','Comprimido 5mg','5mg','Comprimido','Oral','Inibidor 5-alfa-redutase','vermelha','branca_comum','1 comp VO 1x/dia','HPB','{"N40"}',false,NULL,4),
('Cialis','Tadalafila','Lilly','Comprimido 5mg','5mg','Comprimido','Oral','Inibidor PDE-5','vermelha','branca_comum','1 comp VO 1x/dia','Disfunção erétil, HPB','{"F52.2","N40"}',false,NULL,4),
('Viagra','Sildenafila','Pfizer','Comprimido 50mg','50mg','Comprimido','Oral','Inibidor PDE-5','vermelha','branca_comum','1 comp VO 30-60 min antes da relação','Disfunção erétil','{"F52.2"}',false,NULL,4),
('Acne Free','Adapaleno','Galderma','Gel 0,1%','1mg/g','Gel tópico','Tópica','Retinoide tópico','vermelha','branca_comum','Aplicar fina camada à noite','Acne','{"L70"}',false,NULL,4),
('Roacutan','Isotretinoína','Roche','Cápsula 20mg','20mg','Cápsula','Oral','Retinoide sistêmico','vermelha','branca_comum','0,5-1mg/kg/dia VO','Acne grave','{"L70.0"}',false,NULL,3),
('Cetoconazol EMS','Cetoconazol','EMS','Shampoo 2%','20mg/g','Shampoo','Tópica','Antifúngico tópico','livre','branca_comum','Aplicar 2x/semana','Dermatite seborreica','{"L21"}',true,'EMS',2),
('Maxidex','Dexametasona','Alcon','Colírio 0,1%','1mg/mL','Colírio','Oftálmica','Corticoide oftálmico','vermelha','branca_comum','1 gota a cada 4-6h','Inflamação ocular','{"H10"}',false,NULL,4),
('Tobradex','Tobramicina + Dexametasona','Alcon','Colírio','3mg+1mg/mL','Colírio','Oftálmica','Antibiótico + corticoide','vermelha','antimicrobiano','1 gota a cada 4-6h','Conjuntivite bacteriana','{"H10"}',false,NULL,4),
('Centrum','Polivitamínico','Pfizer','Comprimido','-','Comprimido','Oral','Polivitamínico','livre','branca_comum','1 comp VO 1x/dia','Suplementação','{"E63"}',false,NULL,3),
('Addera D3','Colecalciferol','Mantecorp','Cápsula 7000 UI','7000 UI','Cápsula','Oral','Vitamina D','livre','branca_comum','1 cáp VO 1x/semana','Deficiência de vitamina D','{"E55"}',false,NULL,4),
('Noripurum','Ferripolimaltose','Takeda','Comprimido 100mg','100mg Fe','Comprimido','Oral','Suplemento de ferro','livre','branca_comum','1 comp VO 1-2x/dia','Anemia ferropriva','{"D50"}',false,NULL,4),
('Sulfato Ferroso EMS','Sulfato Ferroso','EMS','Comprimido 40mg','40mg Fe elem','Comprimido','Oral','Suplemento de ferro','livre','branca_comum','1 comp VO 1-3x/dia','Anemia ferropriva','{"D50"}',true,'EMS',2),
('Folifolin','Ácido Fólico','Eurofarma','Comprimido 5mg','5mg','Comprimido','Oral','Vitamina B9','livre','branca_comum','1 comp VO 1x/dia','Gestação, anemia megaloblástica','{"D52","Z34"}',true,'Eurofarma',2)
ON CONFLICT (nome_comercial) DO NOTHING;
